// Code generated by genx:model DO NOT EDIT.
package v2

import (
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
	"github.com/xoctopus/sqlx/testdata"
)

var TUser *tUser

func init() {
	m := modeled.M[User]()
	TUser = &tUser{
		Table: m,
		I: iUser{
			Primary:  m.MK("primary"),
			IGender:  m.MK("i_gender"),
			UIUserID: m.MK("ui_user_id"),
			UIName:   m.MK("ui_name"),
		},
		ID:        modeled.CT[User, uint64](m.C("ID")),
		UserID:    modeled.CT[User, testdata.UserID](m.C("UserID")),
		OrgID:     modeled.CT[User, testdata.OrgID](m.C("OrgID")),
		Name:      modeled.CT[User, string](m.C("Name")),
		RealName:  modeled.CT[User, string](m.C("RealName")),
		Age:       modeled.CT[User, int8](m.C("Age")),
		Username:  modeled.CT[User, string](m.C("Username")),
		Nickname:  modeled.CT[User, string](m.C("Nickname")),
		Gender:    modeled.CT[User, testdata.Gender](m.C("Gender")),
		Desc:      modeled.CT[User, string](m.C("Desc")),
		CreatedAt: modeled.CT[User, sqltime.Datetime](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[User, sqltime.Datetime](m.C("UpdatedAt")),
	}
}

// iUser includes all modeled indexes of User
type iUser struct {
	Primary  modeled.Key[User]
	IGender  modeled.Key[User]
	UIUserID modeled.Key[User]
	UIName   modeled.Key[User]
}

// tUser includes modeled table, indexes and column list.
type tUser struct {
	modeled.Table[User]
	I iUser

	ID modeled.TCol[User, uint64]
	// UserID 用户ID
	UserID modeled.TCol[User, testdata.UserID]
	// OrgID 组织ID
	OrgID modeled.TCol[User, testdata.OrgID]
	// Name deprecated to RealName
	Name modeled.TCol[User, string]
	// RealName 用户真实姓名 width changed from 127 to 255
	RealName modeled.TCol[User, string]
	// Age 年龄 datatype changed from int to int8
	Age modeled.TCol[User, int8]
	// Username deprecated
	Username modeled.TCol[User, string]
	// Nickname 用户昵称 deprecated has indexed before
	Nickname modeled.TCol[User, string]
	// Gender 性别 no change
	Gender modeled.TCol[User, testdata.Gender]
	// Desc 描述 new added
	Desc modeled.TCol[User, string]
	// CreatedAt 创建日期时间(秒)
	CreatedAt modeled.TCol[User, sqltime.Datetime]
	// UpdatedAt 更新日期时间(秒)
	UpdatedAt modeled.TCol[User, sqltime.Datetime]
}

// New creates a new User
func (t *tUser) New() builder.Model {
	return &User{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tUser) AssignmentFor(m *User, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of User
func (m User) TableName() string {
	return "t_user"
}

// TableDesc returns descriptions of User
func (m User) TableDesc() []string {
	return []string{
		"User 用户表V2",
	}
}

// PrimaryKey returns column list of User's primary key
func (m User) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of User
func (m User) Indexes() map[string][]string {
	return map[string][]string{
		"i_gender": {
			"Gender",
		},
	}
}

// UniqueIndexes returns unique index list of User
func (m User) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_user_id": {
			"UserID",
		},
		"ui_name": {
			"RealName",
		},
	}
}
