// Code generated by genx:model@(devel) DO NOT EDIT.
package v2

import (
	"context"
	"reflect"

	"github.com/xoctopus/x/codex"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/errors"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
	"github.com/xoctopus/sqlx/testdata"
)

var TUser *tUser
var TagsUser = map[string]string{
	"f_id":         "f_id",
	"f_user_id":    "f_user_id",
	"f_org_id":     "f_org_id",
	"f_name":       "f_name",
	"f_real_name":  "f_real_name",
	"f_age":        "f_age",
	"f_username":   "f_username",
	"f_nick_name":  "f_nick_name",
	"f_gender":     "f_gender",
	"f_desc":       "f_desc",
	"f_created_at": "f_created_at",
	"createdAt":    "f_created_at",
	"f_updated_at": "f_updated_at",
	"updatedAt":    "f_updated_at",
}

func init() {
	m := modeled.M[User]()
	TUser = &tUser{
		Table: m,
		I: iUser{
			Primary:  m.MK("primary"),
			IGender:  m.MK("i_gender"),
			UIUserID: m.MK("ui_user_id"),
			UIName:   m.MK("ui_name"),
		},
		ID:        modeled.CT[User, uint64](m.C("ID")),
		UserID:    modeled.CT[User, testdata.UserID](m.C("UserID")),
		OrgID:     modeled.CT[User, testdata.OrgID](m.C("OrgID")),
		Name:      modeled.CT[User, string](m.C("Name")),
		RealName:  modeled.CT[User, string](m.C("RealName")),
		Age:       modeled.CT[User, int8](m.C("Age")),
		Username:  modeled.CT[User, string](m.C("Username")),
		Nickname:  modeled.CT[User, string](m.C("Nickname")),
		Gender:    modeled.CT[User, testdata.Gender](m.C("Gender")),
		Desc:      modeled.CT[User, string](m.C("Desc")),
		CreatedAt: modeled.CT[User, sqltime.Datetime](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[User, sqltime.Datetime](m.C("UpdatedAt")),
	}
}

// iUser includes all modeled indexes of User
type iUser struct {
	Primary  modeled.Key[User]
	IGender  modeled.Key[User]
	UIUserID modeled.Key[User]
	UIName   modeled.Key[User]
}

// tUser includes modeled table, indexes and column list.
type tUser struct {
	modeled.Table[User]
	I      iUser
	schema string

	ID modeled.TCol[User, uint64]
	// 用户ID
	UserID modeled.TCol[User, testdata.UserID]
	// 组织ID
	OrgID modeled.TCol[User, testdata.OrgID]
	// deprecated to RealName
	Name modeled.TCol[User, string]
	// 用户真实姓名 width changed from 127 to 255
	RealName modeled.TCol[User, string]
	// 年龄 datatype changed from int to int8
	Age modeled.TCol[User, int8]
	// deprecated
	Username modeled.TCol[User, string]
	// 用户昵称 deprecated has indexed before
	Nickname modeled.TCol[User, string]
	// 性别 no change
	Gender modeled.TCol[User, testdata.Gender]
	// 描述 new added
	Desc modeled.TCol[User, string]
	// 创建日期时间(秒)
	CreatedAt modeled.TCol[User, sqltime.Datetime]
	// 更新日期时间(秒)
	UpdatedAt modeled.TCol[User, sqltime.Datetime]
}

// New creates a new User
func (t *tUser) New() builder.Model {
	return &User{}
}

// TagFor returns column tag mapping by name
func (t *tUser) TagFor(name string) (string, bool) {
	v, ok := TagsUser[name]
	return v, ok
}

// AssignmentFor returns assignment by m with expects columns
func (t *tUser) AssignmentFor(m *User, expects ...builder.Col) builder.Assignment {
	cs := t.Pick()
	if len(expects) > 0 {
		cs = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cs.Len())
	cols := make([]builder.Col, 0, cs.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cs.Cols() {
		if !builder.GetColDef(c).AutoInc {
			cols = append(cols, c)
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(builder.ColsOf(cols...), vals...)
}

// WithSchema with schema for tUser
func (t *tUser) WithSchema(s string) builder.Table {
	t.schema = s
	return t
}

// Schema returns schema of tUser
func (t tUser) Schema() string {
	return t.schema
}

// TableName returns database table name of User
func (m User) TableName() string {
	return "t_user"
}

// TableDesc returns descriptions of User
func (m User) TableDesc() []string {
	return []string{
		"用户表V2",
	}
}

// PrimaryKey returns column list of User's primary key
func (m User) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of User
func (m User) Indexes() map[string][]string {
	return map[string][]string{
		"i_gender": {
			"Gender",
		},
	}
}

// UniqueIndexes returns unique index list of User
func (m User) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_user_id": {
			"UserID",
		},
		"ui_name": {
			"RealName",
		},
	}
}

// ColumnRel presents soft foreign key of columns
func (m User) ColumnRel() map[string][]string {
	return map[string][]string{}
}

// Create inserts User to database
func (m *User) Create(ctx context.Context) error {
	m.MarkCreatedAt()
	cols, values := helper.CVsForInsertion(m)
	_, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TUser,
			builder.Comment("User.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch User datalist with condition and additions
func (m *User) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]User, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("User.List"),
	)
	rows, err := session.MustFor(ctx, TUser).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TUser, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]User)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// Count record count of User match condition
func (m *User) Count(ctx context.Context, cond builder.SqlCondition) (int64, error) {
	conds := []frag.Fragment{cond}
	adds := builder.Additions{
		builder.Where(builder.And(conds...)),
		builder.Comment("User.Count"),
	}
	rows, err := session.MustFor(ctx, TUser).Adaptor().Query(
		ctx,
		builder.Select(builder.Count()).From(TUser, adds...),
	)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	count := int64(0)
	if err = helper.Scan(ctx, rows, &count); err != nil {
		return 0, err
	}
	return count, nil
}

// FetchByID fetch User by User.ID
func (m *User) FetchByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
	}
	rows, err := session.MustFor(ctx, TUser).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("User.FetchByID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByUserID fetch User by User.UserID
func (m *User) FetchByUserID(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
	}
	rows, err := session.MustFor(ctx, TUser).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("User.FetchByUserID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByRealName fetch User by User.RealName
func (m *User) FetchByRealName(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.RealName.AsCond(builder.Eq(m.RealName)),
	}
	rows, err := session.MustFor(ctx, TUser).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("User.FetchByRealName"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// UpdateByID update User by User.ID
func (m *User) UpdateByID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
	}
	res, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.UpdateByID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByID update User by User.ID and retrieve record
func (m *User) UpdateAndFetchByID(ctx context.Context, targets ...builder.Col) error {
	return session.MustFor(ctx, TUser).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByUserID update User by User.UserID
func (m *User) UpdateByUserID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
	}
	res, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.UpdateByUserID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByUserID update User by User.UserID and retrieve record
func (m *User) UpdateAndFetchByUserID(ctx context.Context, targets ...builder.Col) error {
	return session.MustFor(ctx, TUser).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByUserID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByUserID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByRealName update User by User.RealName
func (m *User) UpdateByRealName(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TUser.RealName.AsCond(builder.Eq(m.RealName)),
	}
	res, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.UpdateByRealName"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByRealName update User by User.RealName and retrieve record
func (m *User) UpdateAndFetchByRealName(ctx context.Context, targets ...builder.Col) error {
	return session.MustFor(ctx, TUser).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByRealName(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByRealName(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// DeleteByID delete User recode by User.ID
func (m *User) DeleteByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
	}
	_, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Comment("User.DeleteByID"),
		),
	)
	return err
}

// DeleteByUserID delete User recode by User.UserID
func (m *User) DeleteByUserID(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
	}
	_, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Comment("User.DeleteByUserID"),
		),
	)
	return err
}

// DeleteByRealName delete User recode by User.RealName
func (m *User) DeleteByRealName(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.RealName.AsCond(builder.Eq(m.RealName)),
	}
	_, err := session.MustFor(ctx, TUser).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Comment("User.DeleteByRealName"),
		),
	)
	return err
}
