// Code generated by genx:doc DO NOT EDIT.
package v2

import (
	"github.com/xoctopus/x/docx"
)

func (v *User) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelUser, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrg, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.UserDataV2, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.CreationModificationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"用户表V2"}, true
}

func (v *UserDataV2) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"deprecated to RealName"}, true
		case "RealName":
			return []string{"用户真实姓名", "width changed from 127 to 255"}, true
		case "Age":
			return []string{"年龄", "datatype changed from int to int8"}, true
		case "Username":
			return []string{"deprecated"}, true
		case "Nickname":
			return []string{"用户昵称 deprecated has indexed before"}, true
		case "Gender":
			return []string{"性别", "no change"}, true
		case "Desc":
			return []string{"描述", "new added"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}
