// Code generated by genx:model@(devel) DO NOT EDIT.
package models

import (
	"context"
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
)

var TEnumeration *tEnumeration
var TagsEnumeration = map[string]string{
	"f_tab":       "f_tab",
	"f_col":       "f_col",
	"f_enum_type": "f_enum_type",
	"f_value":     "f_value",
	"f_kind":      "f_kind",
	"f_key":       "f_key",
	"f_text":      "f_text",
}

func init() {
	m := modeled.M[Enumeration]()
	TEnumeration = &tEnumeration{
		Table:    m,
		I:        iEnumeration{},
		Model:    modeled.CT[Enumeration, string](m.C("Model")),
		Col:      modeled.CT[Enumeration, string](m.C("Col")),
		EnumType: modeled.CT[Enumeration, string](m.C("EnumType")),
		Value:    modeled.CT[Enumeration, string](m.C("Value")),
		Kind:     modeled.CT[Enumeration, string](m.C("Kind")),
		Key:      modeled.CT[Enumeration, string](m.C("Key")),
		Text:     modeled.CT[Enumeration, string](m.C("Text")),
	}
	MetaCatalog.Add(TEnumeration)
}

// iEnumeration includes all modeled indexes of Enumeration
type iEnumeration struct {
}

// tEnumeration includes modeled table, indexes and column list.
type tEnumeration struct {
	modeled.Table[Enumeration]
	I      iEnumeration
	schema string

	Model    modeled.TCol[Enumeration, string]
	Col      modeled.TCol[Enumeration, string]
	EnumType modeled.TCol[Enumeration, string]
	Value    modeled.TCol[Enumeration, string]
	Kind     modeled.TCol[Enumeration, string]
	Key      modeled.TCol[Enumeration, string]
	Text     modeled.TCol[Enumeration, string]
}

// New creates a new Enumeration
func (t *tEnumeration) New() builder.Model {
	return &Enumeration{}
}

// TagFor returns column tag mapping by name
func (t *tEnumeration) TagFor(name string) (string, bool) {
	v, ok := TagsEnumeration[name]
	return v, ok
}

// AssignmentFor returns assignment by m with expects columns
func (t *tEnumeration) AssignmentFor(m *Enumeration, expects ...builder.Col) builder.Assignment {
	cs := t.Pick()
	if len(expects) > 0 {
		cs = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cs.Len())
	cols := make([]builder.Col, 0, cs.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cs.Cols() {
		if !builder.GetColDef(c).AutoInc {
			cols = append(cols, c)
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(builder.ColsOf(cols...), vals...)
}

// WithSchema with schema for tEnumeration
func (t *tEnumeration) WithSchema(s string) builder.Table {
	t.schema = s
	return t
}

// Schema returns schema of tEnumeration
func (t tEnumeration) Schema() string {
	return t.schema
}

// TableName returns database table name of Enumeration
func (m Enumeration) TableName() string {
	return "sql_meta_enumeration"
}

// TableDesc returns descriptions of Enumeration
func (m Enumeration) TableDesc() []string {
	return []string{}
}

// PrimaryKey returns column list of Enumeration's primary key
func (m Enumeration) PrimaryKey() []string {
	return []string{}
}

// Indexes returns index list of Enumeration
func (m Enumeration) Indexes() map[string][]string {
	return map[string][]string{}
}

// UniqueIndexes returns unique index list of Enumeration
func (m Enumeration) UniqueIndexes() map[string][]string {
	return map[string][]string{}
}

// ColumnRel presents soft foreign key of columns
func (m Enumeration) ColumnRel() map[string][]string {
	return map[string][]string{}
}

// Create inserts Enumeration to database
func (m *Enumeration) Create(ctx context.Context) error {
	cols, values := helper.CVsForInsertion(m)
	_, err := session.MustFor(ctx, TEnumeration).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TEnumeration,
			builder.Comment("Enumeration.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch Enumeration datalist with condition and additions
func (m *Enumeration) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]Enumeration, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("Enumeration.List"),
	)
	rows, err := session.MustFor(ctx, TEnumeration).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TEnumeration, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]Enumeration)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// Count record count of Enumeration match condition
func (m *Enumeration) Count(ctx context.Context, cond builder.SqlCondition) (int64, error) {
	conds := []frag.Fragment{cond}
	adds := builder.Additions{
		builder.Where(builder.And(conds...)),
		builder.Comment("Enumeration.Count"),
	}
	rows, err := session.MustFor(ctx, TEnumeration).Adaptor().Query(
		ctx,
		builder.Select(builder.Count()).From(TEnumeration, adds...),
	)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	count := int64(0)
	if err = helper.Scan(ctx, rows, &count); err != nil {
		return 0, err
	}
	return count, nil
}
