// Code generated by genx:model@(devel) DO NOT EDIT.
package models

import (
	"context"
	"reflect"

	"github.com/xoctopus/x/codex"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/errors"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
)

var TTableColumn *tTableColumn
var TagsTableColumn = map[string]string{
	"f_tab":     "f_tab",
	"f_col":     "f_col",
	"f_col_typ": "f_col_typ",
	"f_field":   "f_field",
	"f_rel":     "f_rel",
	"f_doc":     "f_doc",
}

func init() {
	m := modeled.M[TableColumn]()
	TTableColumn = &tTableColumn{
		Table: m,
		I: iTableColumn{
			UIColumn: m.MK("ui_column"),
		},
		Model:   modeled.CT[TableColumn, string](m.C("Model")),
		Col:     modeled.CT[TableColumn, string](m.C("Col")),
		ColType: modeled.CT[TableColumn, string](m.C("ColType")),
		Field:   modeled.CT[TableColumn, string](m.C("Field")),
		Rel:     modeled.CT[TableColumn, string](m.C("Rel")),
		Comment: modeled.CT[TableColumn, string](m.C("Comment")),
	}
	MetaCatalog.Add(TTableColumn)
}

// iTableColumn includes all modeled indexes of TableColumn
type iTableColumn struct {
	UIColumn modeled.Key[TableColumn]
}

// tTableColumn includes modeled table, indexes and column list.
type tTableColumn struct {
	modeled.Table[TableColumn]
	I      iTableColumn
	schema string

	Model   modeled.TCol[TableColumn, string]
	Col     modeled.TCol[TableColumn, string]
	ColType modeled.TCol[TableColumn, string]
	Field   modeled.TCol[TableColumn, string]
	Rel     modeled.TCol[TableColumn, string]
	Comment modeled.TCol[TableColumn, string]
}

// New creates a new TableColumn
func (t *tTableColumn) New() builder.Model {
	return &TableColumn{}
}

// TagFor returns column tag mapping by name
func (t *tTableColumn) TagFor(name string) (string, bool) {
	v, ok := TagsTableColumn[name]
	return v, ok
}

// AssignmentFor returns assignment by m with expects columns
func (t *tTableColumn) AssignmentFor(m *TableColumn, expects ...builder.Col) builder.Assignment {
	cs := t.Pick()
	if len(expects) > 0 {
		cs = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cs.Len())
	cols := make([]builder.Col, 0, cs.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cs.Cols() {
		if !builder.GetColDef(c).AutoInc {
			cols = append(cols, c)
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(builder.ColsOf(cols...), vals...)
}

// WithSchema with schema for tTableColumn
func (t *tTableColumn) WithSchema(s string) builder.Table {
	t.schema = s
	return t
}

// Schema returns schema of tTableColumn
func (t tTableColumn) Schema() string {
	return t.schema
}

// TableName returns database table name of TableColumn
func (m TableColumn) TableName() string {
	return "sql_meta_table_column"
}

// TableDesc returns descriptions of TableColumn
func (m TableColumn) TableDesc() []string {
	return []string{}
}

// PrimaryKey returns column list of TableColumn's primary key
func (m TableColumn) PrimaryKey() []string {
	return []string{}
}

// Indexes returns index list of TableColumn
func (m TableColumn) Indexes() map[string][]string {
	return map[string][]string{}
}

// UniqueIndexes returns unique index list of TableColumn
func (m TableColumn) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_column": {
			"Model",
			"Col",
		},
	}
}

// ColumnRel presents soft foreign key of columns
func (m TableColumn) ColumnRel() map[string][]string {
	return map[string][]string{}
}

// Create inserts TableColumn to database
func (m *TableColumn) Create(ctx context.Context) error {
	cols, values := helper.CVsForInsertion(m)
	_, err := session.MustFor(ctx, TTableColumn).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TTableColumn,
			builder.Comment("TableColumn.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch TableColumn datalist with condition and additions
func (m *TableColumn) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]TableColumn, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("TableColumn.List"),
	)
	rows, err := session.MustFor(ctx, TTableColumn).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TTableColumn, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]TableColumn)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// Count record count of TableColumn match condition
func (m *TableColumn) Count(ctx context.Context, cond builder.SqlCondition) (int64, error) {
	conds := []frag.Fragment{cond}
	adds := builder.Additions{
		builder.Where(builder.And(conds...)),
		builder.Comment("TableColumn.Count"),
	}
	rows, err := session.MustFor(ctx, TTableColumn).Adaptor().Query(
		ctx,
		builder.Select(builder.Count()).From(TTableColumn, adds...),
	)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	count := int64(0)
	if err = helper.Scan(ctx, rows, &count); err != nil {
		return 0, err
	}
	return count, nil
}

// FetchByModelAndCol fetch TableColumn by TableColumn.Model and TableColumn.Col
func (m *TableColumn) FetchByModelAndCol(ctx context.Context) error {
	conds := []frag.Fragment{
		TTableColumn.Model.AsCond(builder.Eq(m.Model)),
		TTableColumn.Col.AsCond(builder.Eq(m.Col)),
	}
	rows, err := session.MustFor(ctx, TTableColumn).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TTableColumn,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("TableColumn.FetchByModelAndCol"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// UpdateByModelAndCol update TableColumn by TableColumn.Model and TableColumn.Col
func (m *TableColumn) UpdateByModelAndCol(ctx context.Context, expects ...builder.Col) error {
	conds := []frag.Fragment{
		TTableColumn.Model.AsCond(builder.Eq(m.Model)),
		TTableColumn.Col.AsCond(builder.Eq(m.Col)),
	}
	res, err := session.MustFor(ctx, TTableColumn).Adaptor().Exec(
		ctx,
		builder.Update(TTableColumn).
			Set(TTableColumn.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("TableColumn.UpdateByModelAndCol"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByModelAndCol update TableColumn by TableColumn.Model and TableColumn.Col and retrieve record
func (m *TableColumn) UpdateAndFetchByModelAndCol(ctx context.Context, targets ...builder.Col) error {
	return session.MustFor(ctx, TTableColumn).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByModelAndCol(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByModelAndCol(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// DeleteByModelAndCol delete TableColumn recode by TableColumn.Model and TableColumn.Col
func (m *TableColumn) DeleteByModelAndCol(ctx context.Context) error {
	conds := []frag.Fragment{
		TTableColumn.Model.AsCond(builder.Eq(m.Model)),
		TTableColumn.Col.AsCond(builder.Eq(m.Col)),
	}
	_, err := session.MustFor(ctx, TTableColumn).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TTableColumn,
			builder.Where(builder.And(conds...)),
			builder.Comment("TableColumn.DeleteByModelAndCol"),
		),
	)
	return err
}
