// Code generated by genx:model@(devel) DO NOT EDIT.
package models

import (
	"context"
	"reflect"

	"github.com/xoctopus/x/codex"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/errors"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
)

var TTable *tTable
var TagsTable = map[string]string{
	"f_tab":      "f_tab",
	"f_tab_type": "f_tab_type",
	"f_doc":      "f_doc",
}

func init() {
	m := modeled.M[Table]()
	TTable = &tTable{
		Table: m,
		I: iTable{
			UIColumn: m.MK("ui_column"),
		},
		Model:   modeled.CT[Table, string](m.C("Model")),
		TabType: modeled.CT[Table, string](m.C("TabType")),
		Comment: modeled.CT[Table, string](m.C("Comment")),
	}
	MetaCatalog.Add(TTable)
}

// iTable includes all modeled indexes of Table
type iTable struct {
	UIColumn modeled.Key[Table]
}

// tTable includes modeled table, indexes and column list.
type tTable struct {
	modeled.Table[Table]
	I      iTable
	schema string

	Model   modeled.TCol[Table, string]
	TabType modeled.TCol[Table, string]
	Comment modeled.TCol[Table, string]
}

// New creates a new Table
func (t *tTable) New() builder.Model {
	return &Table{}
}

// TagFor returns column tag mapping by name
func (t *tTable) TagFor(name string) (string, bool) {
	v, ok := TagsTable[name]
	return v, ok
}

// AssignmentFor returns assignment by m with expects columns
func (t *tTable) AssignmentFor(m *Table, expects ...builder.Col) builder.Assignment {
	cs := t.Pick()
	if len(expects) > 0 {
		cs = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cs.Len())
	cols := make([]builder.Col, 0, cs.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cs.Cols() {
		if !builder.GetColDef(c).AutoInc {
			cols = append(cols, c)
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(builder.ColsOf(cols...), vals...)
}

// WithSchema with schema for tTable
func (t *tTable) WithSchema(s string) builder.Table {
	t.schema = s
	return t
}

// Schema returns schema of tTable
func (t tTable) Schema() string {
	return t.schema
}

// TableName returns database table name of Table
func (m Table) TableName() string {
	return "sql_meta_table"
}

// TableDesc returns descriptions of Table
func (m Table) TableDesc() []string {
	return []string{}
}

// PrimaryKey returns column list of Table's primary key
func (m Table) PrimaryKey() []string {
	return []string{}
}

// Indexes returns index list of Table
func (m Table) Indexes() map[string][]string {
	return map[string][]string{}
}

// UniqueIndexes returns unique index list of Table
func (m Table) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_column": {
			"Model",
		},
	}
}

// ColumnRel presents soft foreign key of columns
func (m Table) ColumnRel() map[string][]string {
	return map[string][]string{}
}

// Create inserts Table to database
func (m *Table) Create(ctx context.Context) error {
	cols, values := helper.CVsForInsertion(m)
	_, err := session.MustFor(ctx, TTable).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TTable,
			builder.Comment("Table.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch Table datalist with condition and additions
func (m *Table) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]Table, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("Table.List"),
	)
	rows, err := session.MustFor(ctx, TTable).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TTable, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]Table)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// Count record count of Table match condition
func (m *Table) Count(ctx context.Context, cond builder.SqlCondition) (int64, error) {
	conds := []frag.Fragment{cond}
	adds := builder.Additions{
		builder.Where(builder.And(conds...)),
		builder.Comment("Table.Count"),
	}
	rows, err := session.MustFor(ctx, TTable).Adaptor().Query(
		ctx,
		builder.Select(builder.Count()).From(TTable, adds...),
	)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	count := int64(0)
	if err = helper.Scan(ctx, rows, &count); err != nil {
		return 0, err
	}
	return count, nil
}

// FetchByModel fetch Table by Table.Model
func (m *Table) FetchByModel(ctx context.Context) error {
	conds := []frag.Fragment{
		TTable.Model.AsCond(builder.Eq(m.Model)),
	}
	rows, err := session.MustFor(ctx, TTable).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TTable,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("Table.FetchByModel"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// UpdateByModel update Table by Table.Model
func (m *Table) UpdateByModel(ctx context.Context, expects ...builder.Col) error {
	conds := []frag.Fragment{
		TTable.Model.AsCond(builder.Eq(m.Model)),
	}
	res, err := session.MustFor(ctx, TTable).Adaptor().Exec(
		ctx,
		builder.Update(TTable).
			Set(TTable.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("Table.UpdateByModel"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByModel update Table by Table.Model and retrieve record
func (m *Table) UpdateAndFetchByModel(ctx context.Context, targets ...builder.Col) error {
	return session.MustFor(ctx, TTable).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByModel(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByModel(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// DeleteByModel delete Table recode by Table.Model
func (m *Table) DeleteByModel(ctx context.Context) error {
	conds := []frag.Fragment{
		TTable.Model.AsCond(builder.Eq(m.Model)),
	}
	_, err := session.MustFor(ctx, TTable).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TTable,
			builder.Where(builder.And(conds...)),
			builder.Comment("Table.DeleteByModel"),
		),
	)
	return err
}
