// Code generated by genx:enum@devel DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[Currency] = (*Currency)(nil)

// ParseCurrency parse Currency from key
func ParseCurrency(key string) (Currency, error) {
	switch key {
	case "CNY":
		return CURRENCY__CNY, nil
	case "USD":
		return CURRENCY__USD, nil
	case "JPY":
		return CURRENCY__JPY, nil
	default:
		var v Currency
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return CURRENCY_UNKNOWN, enumx.ParseErrorFor[Currency](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (Currency) EnumValues() []any {
	return []any{
		CURRENCY__CNY,
		CURRENCY__USD,
		CURRENCY__JPY,
	}
}

// Values returns enum value list of Currency
func (Currency) Values() []Currency {
	return []Currency{
		CURRENCY__CNY,
		CURRENCY__USD,
		CURRENCY__JPY,
	}
}

// String returns v's string as key
func (v Currency) String() string {
	switch v {
	case CURRENCY__CNY:
		return "CNY"
	case CURRENCY__USD:
		return "USD"
	case CURRENCY__JPY:
		return "JPY"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v Currency) Text() string {
	switch v {
	case CURRENCY__CNY:
		return "人民币"
	case CURRENCY__USD:
		return "美元"
	case CURRENCY__JPY:
		return "日元"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v Currency) IsZero() bool {
	return v == CURRENCY_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v Currency) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *Currency) UnmarshalText(data []byte) error {
	vv, err := ParseCurrency(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v Currency) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *Currency) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = Currency(i)
	return nil
}
