// Code generated by genx:enum@devel DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[OrderStatus] = (*OrderStatus)(nil)

// ParseOrderStatus parse OrderStatus from key
func ParseOrderStatus(key string) (OrderStatus, error) {
	switch key {
	case "CREATED":
		return ORDER_STATUS__CREATED, nil
	case "PROCESSING":
		return ORDER_STATUS__PROCESSING, nil
	case "FINISHED":
		return ORDER_STATUS__FINISHED, nil
	case "CANCELED":
		return ORDER_STATUS__CANCELED, nil
	default:
		var v OrderStatus
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return ORDER_STATUS_UNKNOWN, enumx.ParseErrorFor[OrderStatus](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (OrderStatus) EnumValues() []any {
	return []any{
		ORDER_STATUS__CREATED,
		ORDER_STATUS__PROCESSING,
		ORDER_STATUS__FINISHED,
		ORDER_STATUS__CANCELED,
	}
}

// Values returns enum value list of OrderStatus
func (OrderStatus) Values() []OrderStatus {
	return []OrderStatus{
		ORDER_STATUS__CREATED,
		ORDER_STATUS__PROCESSING,
		ORDER_STATUS__FINISHED,
		ORDER_STATUS__CANCELED,
	}
}

// String returns v's string as key
func (v OrderStatus) String() string {
	switch v {
	case ORDER_STATUS__CREATED:
		return "CREATED"
	case ORDER_STATUS__PROCESSING:
		return "PROCESSING"
	case ORDER_STATUS__FINISHED:
		return "FINISHED"
	case ORDER_STATUS__CANCELED:
		return "CANCELED"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v OrderStatus) Text() string {
	switch v {
	case ORDER_STATUS__CREATED:
		return "已创建"
	case ORDER_STATUS__PROCESSING:
		return "处理中"
	case ORDER_STATUS__FINISHED:
		return "已完成"
	case ORDER_STATUS__CANCELED:
		return "已取消"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v OrderStatus) IsZero() bool {
	return v == ORDER_STATUS_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v OrderStatus) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *OrderStatus) UnmarshalText(data []byte) error {
	vv, err := ParseOrderStatus(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v OrderStatus) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *OrderStatus) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = OrderStatus(i)
	return nil
}
