// Code generated by genx:enum@v0.3.8 DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[ProductStatus] = (*ProductStatus)(nil)

// ParseProductStatus parse ProductStatus from key
func ParseProductStatus(key string) (ProductStatus, error) {
	switch key {
	case "ON_SALE":
		return PRODUCT_STATUS__ON_SALE, nil
	case "DISABLED":
		return PRODUCT_STATUS__DISABLED, nil
	default:
		var v ProductStatus
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return PRODUCT_STATUS_UNKNOWN, enumx.ParseErrorFor[ProductStatus](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (ProductStatus) EnumValues() []any {
	return []any{
		PRODUCT_STATUS__ON_SALE,
		PRODUCT_STATUS__DISABLED,
	}
}

// Values returns enum value list of ProductStatus
func (ProductStatus) Values() []ProductStatus {
	return []ProductStatus{
		PRODUCT_STATUS__ON_SALE,
		PRODUCT_STATUS__DISABLED,
	}
}

// String returns v's string as key
func (v ProductStatus) String() string {
	switch v {
	case PRODUCT_STATUS__ON_SALE:
		return "ON_SALE"
	case PRODUCT_STATUS__DISABLED:
		return "DISABLED"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v ProductStatus) Text() string {
	switch v {
	case PRODUCT_STATUS__ON_SALE:
		return "售卖中"
	case PRODUCT_STATUS__DISABLED:
		return "关闭"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v ProductStatus) IsZero() bool {
	return v == PRODUCT_STATUS_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v ProductStatus) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *ProductStatus) UnmarshalText(data []byte) error {
	vv, err := ParseProductStatus(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v ProductStatus) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *ProductStatus) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = ProductStatus(i)
	return nil
}
