// Code generated by genx:enum@(devel) DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[ShipmentStatus] = (*ShipmentStatus)(nil)

// ParseShipmentStatus parse ShipmentStatus from key
func ParseShipmentStatus(key string) (ShipmentStatus, error) {
	switch key {
	case "CREATED":
		return SHIPMENT_STATUS__CREATED, nil
	case "SHIPPING":
		return SHIPMENT_STATUS__SHIPPING, nil
	case "FINISHED":
		return SHIPMENT_STATUS__FINISHED, nil
	default:
		var v ShipmentStatus
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return SHIPMENT_STATUS_UNKNOWN, enumx.ParseErrorFor[ShipmentStatus](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (ShipmentStatus) EnumValues() []any {
	return []any{
		SHIPMENT_STATUS__CREATED,
		SHIPMENT_STATUS__SHIPPING,
		SHIPMENT_STATUS__FINISHED,
	}
}

// Values returns enum value list of ShipmentStatus
func (ShipmentStatus) Values() []ShipmentStatus {
	return []ShipmentStatus{
		SHIPMENT_STATUS__CREATED,
		SHIPMENT_STATUS__SHIPPING,
		SHIPMENT_STATUS__FINISHED,
	}
}

// String returns v's string as key
func (v ShipmentStatus) String() string {
	switch v {
	case SHIPMENT_STATUS__CREATED:
		return "CREATED"
	case SHIPMENT_STATUS__SHIPPING:
		return "SHIPPING"
	case SHIPMENT_STATUS__FINISHED:
		return "FINISHED"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v ShipmentStatus) Text() string {
	switch v {
	case SHIPMENT_STATUS__CREATED:
		return "已创建"
	case SHIPMENT_STATUS__SHIPPING:
		return "运输中"
	case SHIPMENT_STATUS__FINISHED:
		return "已完成"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v ShipmentStatus) IsZero() bool {
	return v == SHIPMENT_STATUS_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v ShipmentStatus) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *ShipmentStatus) UnmarshalText(data []byte) error {
	vv, err := ParseShipmentStatus(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v ShipmentStatus) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *ShipmentStatus) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = ShipmentStatus(i)
	return nil
}
