// Code generated by genx:enum DO NOT EDIT.
package enums

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[UserStatus] = (*UserStatus)(nil)

// ParseUserStatus parse UserStatus from key
func ParseUserStatus(key string) (UserStatus, error) {
	switch key {
	case "ACTIVITY":
		return USER_STATUS__ACTIVITY, nil
	case "DISABLED":
		return USER_STATUS__DISABLED, nil
	default:
		var v UserStatus
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return USER_STATUS_UNKNOWN, enumx.ParseErrorFor[UserStatus](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (UserStatus) EnumValues() []any {
	return []any{
		USER_STATUS__ACTIVITY,
		USER_STATUS__DISABLED,
	}
}

// Values returns enum value list of UserStatus
func (UserStatus) Values() []UserStatus {
	return []UserStatus{
		USER_STATUS__ACTIVITY,
		USER_STATUS__DISABLED,
	}
}

// String returns v's string as key
func (v UserStatus) String() string {
	switch v {
	case USER_STATUS__ACTIVITY:
		return "ACTIVITY"
	case USER_STATUS__DISABLED:
		return "DISABLED"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v UserStatus) Text() string {
	switch v {
	case USER_STATUS__ACTIVITY:
		return "活跃"
	case USER_STATUS__DISABLED:
		return "关闭"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v UserStatus) IsZero() bool {
	return v == USER_STATUS_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v UserStatus) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *UserStatus) UnmarshalText(data []byte) error {
	vv, err := ParseUserStatus(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v UserStatus) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *UserStatus) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = UserStatus(i)
	return nil
}
