// Code generated by genx:doc@(devel) DO NOT EDIT.
package enums

func (v *Currency) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"货币种类"}, true
}

func (v *OrderStatus) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"订单状态"}, true
}

func (v *ProductStatus) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"产品状态"}, true
}

func (v *ShipmentStatus) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"物流状态"}, true
}

func (v *UserStatus) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"用户状态"}, true
}
