// Code generated by genx:doc@devel DO NOT EDIT.
package types

import (
	"github.com/xoctopus/x/docx"
)

func (v *ArrayAsList[T]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *AutoIncID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *ID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *Bool) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"a ternary boolean state UNKNOWN, TRUE or FALSE"}, true
}

func (v *Decimal) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		return []string{}, false
	}
	return []string{"decimal number"}, true
}

func (v *JSONDBType) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *JSONArray[T]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "v":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *JSONObject[T]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "v":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Blob) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"nullable binary"}, true
}

func (v *Text) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"nullable text"}, true
}

func (v *CreationDatetime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建日期时间(秒)"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationDatetime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新日期时间(秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationDeletionDatetime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除日期时间(秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationDatetimeMilli) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建日期时间(毫秒)"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationDatetimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新日期时间(毫秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationDatetimeMilli, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationDeletionDatetimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除日期时间(毫秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationDatetimePrecise, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationTime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建时间 秒时间戳"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationTime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新时间 秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationDeletionTime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除时间 秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationTimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建时间 毫秒时间戳"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationTimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新时间 毫秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationTimePrecise, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *CreationModificationDeletionTimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除时间 毫秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationTimePrecise, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}
