// Code generated by genx:doc@v0.3.8 DO NOT EDIT.
package types

import (
	"github.com/xoctopus/x/docx"
)

func (v *ArrayAsList[T]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"stores a typed slice as a comma-separated TEXT column."}, true
}

func (v *AutoIncID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"is an auto-increment primary key field.", "Deprecated: use [Serial] instead. uint64 conflicts with database/sql's", "int64-centric Value model (see Serial)."}, true
}

func (v *ID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"is a generic unsigned identifier."}, true
}

func (v *Serial) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{"自增主键"}, true
		}
		return []string{}, false
	}
	return []string{"is an auto-increment primary key embed (column f_id).", "ID is int64 rather than uint64 for two reasons:", "1. SQL integer types used for identity columns are signed in the SQL", "standard and in common dialects (INTEGER / BIGINT; PostgreSQL SERIAL /", "BIGSERIAL map to signed integers). Unsigned 64-bit integers are not a", "portable auto-increment type across databases.", "2. database/sql treats integer driver.Value as int64. Passing a uint64 with", "the high bit set (value >= 1<<63) fails with", "\"uint64 values with high bit set are not supported\". Result.LastInsertId", "also returns int64. Using int64 keeps insert args, scan targets, and", "last-insert-id in one representation without conversion edge cases.", "ref:", "- https://pkg.go.dev/database/sql/driver#Value", "- https://www.postgresql.org/docs/current/datatype-numeric.html"}, true
}

func (v *Bool) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"a ternary boolean state UNKNOWN, TRUE or FALSE"}, true
}

func (v *Decimal) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		return []string{}, false
	}
	return []string{"decimal number"}, true
}

func (v *JSONDBType) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"holds an optional SQL datatype override for JSON columns."}, true
}

func (v *JSONArray[T]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "v":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"stores a typed slice as JSON TEXT."}, true
}

func (v *JSONObject[T]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "v":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"stores a typed struct/map as JSON TEXT."}, true
}

func (v *Blob) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"nullable binary"}, true
}

func (v *Text) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"nullable text"}, true
}

func (v *CreationDatetime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建日期时间(秒)"}, true
		}
		return []string{}, false
	}
	return []string{"holds CreatedAt as a second-precision datetime."}, true
}

func (v *CreationModificationDatetime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新日期时间(秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds UpdatedAt to CreationDatetime."}, true
}

func (v *CreationModificationDeletionDatetime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除日期时间(秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds soft-deletion DeletedAt."}, true
}

func (v *CreationDatetimeMilli) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建日期时间(毫秒)"}, true
		}
		return []string{}, false
	}
	return []string{"holds CreatedAt as a millisecond-precision datetime."}, true
}

func (v *CreationModificationDatetimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新日期时间(毫秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationDatetimeMilli, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds UpdatedAt to CreationDatetimeMilli."}, true
}

func (v *CreationModificationDeletionDatetimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除日期时间(毫秒)"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationDatetimePrecise, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds soft-deletion DeletedAt."}, true
}

func (v *CreationTime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建时间 秒时间戳"}, true
		}
		return []string{}, false
	}
	return []string{"holds CreatedAt as a second-precision unix timestamp."}, true
}

func (v *CreationModificationTime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新时间 秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds UpdatedAt to CreationTime."}, true
}

func (v *CreationModificationDeletionTime) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除时间 秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds soft-deletion DeletedAt."}, true
}

func (v *CreationTimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{"创建时间 毫秒时间戳"}, true
		}
		return []string{}, false
	}
	return []string{"holds CreatedAt as a millisecond unix timestamp."}, true
}

func (v *CreationModificationTimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{"更新时间 毫秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationTimePrecise, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds UpdatedAt to CreationTimePrecise."}, true
}

func (v *CreationModificationDeletionTimePrecise) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{"删除时间 毫秒时间戳"}, true
		}
		if doc, ok := docx.Of(&v.CreationModificationTimePrecise, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"adds soft-deletion DeletedAt."}, true
}

func (v *ULID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := docx.Of(&v.ULID, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}
