// Code generated by genx:model DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TOrderSnapshot *tOrderSnapshot

func init() {
	m := modeled.M[OrderSnapshot]()
	TOrderSnapshot = &tOrderSnapshot{
		Table: m,
		I: iOrderSnapshot{
			Primary:      m.MK("primary"),
			IProductName: m.MK("i_product_name"),
			ICreatedAt:   m.MK("i_created_at"),
			UIOrderID:    m.MK("ui_order_id"),
		},
		ID:          modeled.CT[OrderSnapshot, uint64](m.C("ID")),
		OrderID:     modeled.CT[OrderSnapshot, OrderID](m.C("OrderID")),
		ProductID:   modeled.CT[OrderSnapshot, ProductID](m.C("ProductID")),
		ProductSKU:  modeled.CT[OrderSnapshot, string](m.C("ProductSKU")),
		ProductName: modeled.CT[OrderSnapshot, string](m.C("ProductName")),
		Price:       modeled.CT[OrderSnapshot, types.Decimal](m.C("Price")),
		Quantity:    modeled.CT[OrderSnapshot, int64](m.C("Quantity")),
		Subtotal:    modeled.CT[OrderSnapshot, types.Decimal](m.C("Subtotal")),
		CreatedAt:   modeled.CT[OrderSnapshot, sqltime.Timestamp](m.C("CreatedAt")),
	}
	Catalog.Add(TOrderSnapshot)
}

// iOrderSnapshot includes all modeled indexes of OrderSnapshot
type iOrderSnapshot struct {
	Primary      modeled.Key[OrderSnapshot]
	IProductName modeled.Key[OrderSnapshot]
	ICreatedAt   modeled.Key[OrderSnapshot]
	UIOrderID    modeled.Key[OrderSnapshot]
}

// tOrderSnapshot includes modeled table, indexes and column list.
type tOrderSnapshot struct {
	modeled.Table[OrderSnapshot]
	I       iOrderSnapshot
	session string

	ID modeled.TCol[OrderSnapshot, uint64]
	// @rel Order.OrderID
	OrderID modeled.TCol[OrderSnapshot, OrderID]
	// @rel Product.ProductID
	ProductID modeled.TCol[OrderSnapshot, ProductID]
	// ProductSKU 产品SKU
	ProductSKU modeled.TCol[OrderSnapshot, string]
	// ProductName 产品名称 Product.Name
	ProductName modeled.TCol[OrderSnapshot, string]
	// Price 产品单价 Product.Price
	Price modeled.TCol[OrderSnapshot, types.Decimal]
	// Quantity 订单产品数量
	Quantity modeled.TCol[OrderSnapshot, int64]
	// Subtotal 订单金额
	Subtotal modeled.TCol[OrderSnapshot, types.Decimal]
	// CreatedAt 创建时间 秒时间戳
	CreatedAt modeled.TCol[OrderSnapshot, sqltime.Timestamp]
}

// New creates a new OrderSnapshot
func (t *tOrderSnapshot) New() builder.Model {
	return &OrderSnapshot{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tOrderSnapshot) AssignmentFor(m *OrderSnapshot, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// WithSession with session for tOrderSnapshot
func (t *tOrderSnapshot) WithSession(s string) *tOrderSnapshot {
	t2 := *t
	t2.session = s
	return &t2
}

// Session returns session of tOrderSnapshot
func (t tOrderSnapshot) Session() string {
	return t.session
}

// TableName returns database table name of OrderSnapshot
func (m OrderSnapshot) TableName() string {
	return "t_order_snapshot"
}

// TableDesc returns descriptions of OrderSnapshot
func (m OrderSnapshot) TableDesc() []string {
	return []string{
		"OrderSnapshot 订单快照",
	}
}

// PrimaryKey returns column list of OrderSnapshot's primary key
func (m OrderSnapshot) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of OrderSnapshot
func (m OrderSnapshot) Indexes() map[string][]string {
	return map[string][]string{
		"i_product_name": {
			"ProductName",
		},
		"i_created_at": {
			"CreatedAt",
		},
	}
}

// UniqueIndexes returns unique index list of OrderSnapshot
func (m OrderSnapshot) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_order_id": {
			"OrderID",
		},
	}
}
