// Code generated by genx:model DO NOT EDIT.
package models

import (
	"context"
	"reflect"

	"github.com/xoctopus/x/codex"

	"github.com/xoctopus/sqlx/example/enums"
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/errors"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
	"github.com/xoctopus/sqlx/pkg/types"
)

var TOrder *tOrder

func init() {
	m := modeled.M[Order]()
	TOrder = &tOrder{
		Table: m,
		I: iOrder{
			Primary:    m.MK("primary"),
			IStatus:    m.MK("i_status"),
			ICreatedAt: m.MK("i_created_at"),
			IUpdatedAt: m.MK("i_updated_at"),
			UIOrderID:  m.MK("ui_order_id"),
		},
		ID:         modeled.CT[Order, uint64](m.C("ID")),
		UserID:     modeled.CT[Order, UserID](m.C("UserID")),
		OrderID:    modeled.CT[Order, OrderID](m.C("OrderID")),
		OrderNo:    modeled.CT[Order, string](m.C("OrderNo")),
		Amount:     modeled.CT[Order, types.Decimal](m.C("Amount")),
		Currency:   modeled.CT[Order, enums.Currency](m.C("Currency")),
		PaidAt:     modeled.CT[Order, types.Timestamp](m.C("PaidAt")),
		CanceledAt: modeled.CT[Order, types.Timestamp](m.C("CanceledAt")),
		Status:     modeled.CT[Order, enums.OrderStatus](m.C("Status")),
		CreatedAt:  modeled.CT[Order, types.Timestamp](m.C("CreatedAt")),
		UpdatedAt:  modeled.CT[Order, types.Timestamp](m.C("UpdatedAt")),
	}
	Catalog.Add(TOrder)
}

// iOrder includes all modeled indexes of Order
type iOrder struct {
	Primary    modeled.Key[Order]
	IStatus    modeled.Key[Order]
	ICreatedAt modeled.Key[Order]
	IUpdatedAt modeled.Key[Order]
	UIOrderID  modeled.Key[Order]
}

// tOrder includes modeled table, indexes and column list.
type tOrder struct {
	modeled.Table[Order]
	I iOrder

	ID modeled.TCol[Order, uint64]
	// @rel User.UserID
	UserID modeled.TCol[Order, UserID]
	// @rel Order.OrderID
	OrderID modeled.TCol[Order, OrderID]
	// OrderNo 订单编号
	OrderNo modeled.TCol[Order, string]
	// Amount 订单金额
	Amount modeled.TCol[Order, types.Decimal]
	// Currency 结算币种
	Currency modeled.TCol[Order, enums.Currency]
	// PaidAt 订单支付时间
	PaidAt modeled.TCol[Order, types.Timestamp]
	// CanceledAt 订单取消时间
	CanceledAt modeled.TCol[Order, types.Timestamp]
	// Status 订单状态
	Status modeled.TCol[Order, enums.OrderStatus]
	// CreatedAt 创建时间 毫秒时间戳
	CreatedAt modeled.TCol[Order, types.Timestamp]
	// UpdatedAt 更新时间 毫秒时间戳
	UpdatedAt modeled.TCol[Order, types.Timestamp]
}

// New creates a new Order
func (t *tOrder) New() builder.Model {
	return &Order{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tOrder) AssignmentFor(m *Order, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of Order
func (m Order) TableName() string {
	return "t_order"
}

// TableDesc returns descriptions of Order
func (m Order) TableDesc() []string {
	return []string{
		"Order 订单",
	}
}

// PrimaryKey returns column list of Order's primary key
func (m Order) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Order
func (m Order) Indexes() map[string][]string {
	return map[string][]string{
		"i_status": {
			"Status",
		},
		"i_created_at": {
			"CreatedAt",
		},
		"i_updated_at": {
			"UpdatedAt",
		},
	}
}

// UniqueIndexes returns unique index list of Order
func (m Order) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_order_id": {
			"OrderID",
		},
	}
}

// Create inserts Order to database
func (m *Order) Create(ctx context.Context) error {
	m.MarkCreatedAt()
	cols, values := helper.ColumnsAndValuesForInsertion(m)
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TOrder,
			builder.Comment("Order.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch Order datalist with condition and additions
func (m *Order) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]Order, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("Order.List"),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TOrder, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]Order)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// FetchByID fetch Order by Order.ID
func (m *Order) FetchByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TOrder.ID.AsCond(builder.Eq(m.ID)),
	}
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TOrder,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("Order.FetchByID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByOrderID fetch Order by Order.OrderID
func (m *Order) FetchByOrderID(ctx context.Context) error {
	conds := []frag.Fragment{
		TOrder.OrderID.AsCond(builder.Eq(m.OrderID)),
	}
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TOrder,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("Order.FetchByOrderID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// UpdateByID update Order by Order.ID
func (m *Order) UpdateByID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TOrder.ID.AsCond(builder.Eq(m.ID)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TOrder).
			Set(TOrder.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("Order.UpdateByID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByID update Order by Order.ID and retrieve record
func (m *Order) UpdateAndFetchByID(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByOrderID update Order by Order.OrderID
func (m *Order) UpdateByOrderID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TOrder.OrderID.AsCond(builder.Eq(m.OrderID)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TOrder).
			Set(TOrder.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("Order.UpdateByOrderID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByOrderID update Order by Order.OrderID and retrieve record
func (m *Order) UpdateAndFetchByOrderID(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByOrderID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByOrderID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// DeleteByID delete Order recode by Order.ID
func (m *Order) DeleteByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TOrder.ID.AsCond(builder.Eq(m.ID)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TOrder,
			builder.Where(builder.And(conds...)),
			builder.Comment("Order.DeleteByID"),
		),
	)
	return err
}

// DeleteByOrderID delete Order recode by Order.OrderID
func (m *Order) DeleteByOrderID(ctx context.Context) error {
	conds := []frag.Fragment{
		TOrder.OrderID.AsCond(builder.Eq(m.OrderID)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TOrder,
			builder.Where(builder.And(conds...)),
			builder.Comment("Order.DeleteByOrderID"),
		),
	)
	return err
}
