// Code generated by genx:model DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/xoctopus/sqlx/example/enums"
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TOrder *tOrder

func init() {
	m := modeled.M[Order]()
	TOrder = &tOrder{
		Table: m,
		I: iOrder{
			Primary:    m.MK("primary"),
			IStatus:    m.MK("i_status"),
			ICreatedAt: m.MK("i_created_at"),
			IUpdatedAt: m.MK("i_updated_at"),
			UIOrderID:  m.MK("ui_order_id"),
		},
		ID:         modeled.CT[Order, uint64](m.C("ID")),
		UserID:     modeled.CT[Order, UserID](m.C("UserID")),
		OrderID:    modeled.CT[Order, OrderID](m.C("OrderID")),
		OrderNo:    modeled.CT[Order, string](m.C("OrderNo")),
		Amount:     modeled.CT[Order, types.Decimal](m.C("Amount")),
		Currency:   modeled.CT[Order, enums.Currency](m.C("Currency")),
		PaidAt:     modeled.CT[Order, sqltime.Timestamp](m.C("PaidAt")),
		CanceledAt: modeled.CT[Order, sqltime.Timestamp](m.C("CanceledAt")),
		Status:     modeled.CT[Order, enums.OrderStatus](m.C("Status")),
		CreatedAt:  modeled.CT[Order, sqltime.Timestamp](m.C("CreatedAt")),
		UpdatedAt:  modeled.CT[Order, sqltime.Timestamp](m.C("UpdatedAt")),
	}
	Catalog.Add(TOrder)
}

// iOrder includes all modeled indexes of Order
type iOrder struct {
	Primary    modeled.Key[Order]
	IStatus    modeled.Key[Order]
	ICreatedAt modeled.Key[Order]
	IUpdatedAt modeled.Key[Order]
	UIOrderID  modeled.Key[Order]
}

// tOrder includes modeled table, indexes and column list.
type tOrder struct {
	modeled.Table[Order]
	I       iOrder
	session string

	ID modeled.TCol[Order, uint64]
	// @rel User.UserID
	UserID modeled.TCol[Order, UserID]
	// @rel Order.OrderID
	OrderID modeled.TCol[Order, OrderID]
	// OrderNo 订单编号
	OrderNo modeled.TCol[Order, string]
	// Amount 订单金额
	Amount modeled.TCol[Order, types.Decimal]
	// Currency 结算币种
	Currency modeled.TCol[Order, enums.Currency]
	// PaidAt 订单支付时间
	PaidAt modeled.TCol[Order, sqltime.Timestamp]
	// CanceledAt 订单取消时间
	CanceledAt modeled.TCol[Order, sqltime.Timestamp]
	// Status 订单状态
	Status modeled.TCol[Order, enums.OrderStatus]
	// CreatedAt 创建时间 秒时间戳
	CreatedAt modeled.TCol[Order, sqltime.Timestamp]
	// UpdatedAt 更新时间 秒时间戳
	UpdatedAt modeled.TCol[Order, sqltime.Timestamp]
}

// New creates a new Order
func (t *tOrder) New() builder.Model {
	return &Order{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tOrder) AssignmentFor(m *Order, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// WithSession with session for tOrder
func (t *tOrder) WithSession(s string) *tOrder {
	t2 := *t
	t2.session = s
	return &t2
}

// Session returns session of tOrder
func (t tOrder) Session() string {
	return t.session
}

// TableName returns database table name of Order
func (m Order) TableName() string {
	return "t_order"
}

// TableDesc returns descriptions of Order
func (m Order) TableDesc() []string {
	return []string{
		"Order 订单",
	}
}

// PrimaryKey returns column list of Order's primary key
func (m Order) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Order
func (m Order) Indexes() map[string][]string {
	return map[string][]string{
		"i_status": {
			"Status",
		},
		"i_created_at": {
			"CreatedAt",
		},
		"i_updated_at": {
			"UpdatedAt",
		},
	}
}

// UniqueIndexes returns unique index list of Order
func (m Order) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_order_id": {
			"OrderID",
		},
	}
}
