// Code generated by genx:model DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/xoctopus/sqlx/example/enums"
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TProduct *tProduct

func init() {
	m := modeled.M[Product]()
	TProduct = &tProduct{
		Table: m,
		I: iProduct{
			Primary:      m.MK("primary"),
			IProductName: m.MK("i_product_name"),
			IStatus:      m.MK("i_status"),
			IUpdatedAt:   m.MK("i_updated_at"),
			UIProductID:  m.MK("ui_product_id"),
		},
		ID:          modeled.CT[Product, uint64](m.C("ID")),
		ProductID:   modeled.CT[Product, ProductID](m.C("ProductID")),
		SKU:         modeled.CT[Product, string](m.C("SKU")),
		Name:        modeled.CT[Product, string](m.C("Name")),
		Description: modeled.CT[Product, string](m.C("Description")),
		Price:       modeled.CT[Product, types.Decimal](m.C("Price")),
		Currency:    modeled.CT[Product, enums.Currency](m.C("Currency")),
		Status:      modeled.CT[Product, enums.ProductStatus](m.C("Status")),
		CreatedAt:   modeled.CT[Product, sqltime.Timestamp](m.C("CreatedAt")),
		UpdatedAt:   modeled.CT[Product, sqltime.Timestamp](m.C("UpdatedAt")),
		DeletedAt:   modeled.CT[Product, sqltime.Timestamp](m.C("DeletedAt")),
	}
	Catalog.Add(TProduct)
}

// iProduct includes all modeled indexes of Product
type iProduct struct {
	Primary      modeled.Key[Product]
	IProductName modeled.Key[Product]
	IStatus      modeled.Key[Product]
	IUpdatedAt   modeled.Key[Product]
	UIProductID  modeled.Key[Product]
}

// tProduct includes modeled table, indexes and column list.
type tProduct struct {
	modeled.Table[Product]
	I       iProduct
	session string

	ID modeled.TCol[Product, uint64]
	// @rel Product.ProductID
	ProductID modeled.TCol[Product, ProductID]
	// SKU 库存标签
	SKU modeled.TCol[Product, string]
	// Name 产品名称
	Name modeled.TCol[Product, string]
	// Description 产品描述
	Description modeled.TCol[Product, string]
	// Price 单价
	Price modeled.TCol[Product, types.Decimal]
	// Currency 货币
	Currency modeled.TCol[Product, enums.Currency]
	// Status 产品销售状态
	Status modeled.TCol[Product, enums.ProductStatus]
	// CreatedAt 创建时间 秒时间戳
	CreatedAt modeled.TCol[Product, sqltime.Timestamp]
	// UpdatedAt 更新时间 秒时间戳
	UpdatedAt modeled.TCol[Product, sqltime.Timestamp]
	// DeletedAt 删除时间 秒时间戳
	DeletedAt modeled.TCol[Product, sqltime.Timestamp]
}

// New creates a new Product
func (t *tProduct) New() builder.Model {
	return &Product{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tProduct) AssignmentFor(m *Product, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// WithSession with session for tProduct
func (t *tProduct) WithSession(s string) *tProduct {
	t2 := *t
	t2.session = s
	return &t2
}

// Session returns session of tProduct
func (t tProduct) Session() string {
	return t.session
}

// TableName returns database table name of Product
func (m Product) TableName() string {
	return "t_product"
}

// TableDesc returns descriptions of Product
func (m Product) TableDesc() []string {
	return []string{
		"Product 商品",
	}
}

// PrimaryKey returns column list of Product's primary key
func (m Product) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Product
func (m Product) Indexes() map[string][]string {
	return map[string][]string{
		"i_product_name": {
			"Name",
		},
		"i_status": {
			"Status",
		},
		"i_updated_at": {
			"UpdatedAt",
		},
	}
}

// UniqueIndexes returns unique index list of Product
func (m Product) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_product_id": {
			"ProductID",
		},
	}
}
