// Code generated by genx:model DO NOT EDIT.
package models

import (
	"context"
	"reflect"

	"github.com/xoctopus/x/codex"

	"github.com/xoctopus/sqlx/example/enums"
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/errors"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TShipment *tShipment

func init() {
	m := modeled.M[Shipment]()
	TShipment = &tShipment{
		Table: m,
		I: iShipment{
			Primary:      m.MK("primary"),
			ICarrier:     m.MK("i_carrier"),
			IStatus:      m.MK("i_status"),
			IShippedAt:   m.MK("i_shipped_at"),
			IDeliveredAt: m.MK("i_delivered_at"),
			UIOrderID:    m.MK("ui_order_id"),
			UITrackingNo: m.MK("ui_tracking_no"),
		},
		ID:          modeled.CT[Shipment, uint64](m.C("ID")),
		OrderID:     modeled.CT[Shipment, OrderID](m.C("OrderID")),
		Carrier:     modeled.CT[Shipment, string](m.C("Carrier")),
		TrackingNo:  modeled.CT[Shipment, string](m.C("TrackingNo")),
		Status:      modeled.CT[Shipment, enums.ShipmentStatus](m.C("Status")),
		ShippedAt:   modeled.CT[Shipment, sqltime.Timestamp](m.C("ShippedAt")),
		DeliveredAt: modeled.CT[Shipment, sqltime.Timestamp](m.C("DeliveredAt")),
		CreatedAt:   modeled.CT[Shipment, sqltime.Timestamp](m.C("CreatedAt")),
		UpdatedAt:   modeled.CT[Shipment, sqltime.Timestamp](m.C("UpdatedAt")),
	}
	Catalog.Add(TShipment)
}

// iShipment includes all modeled indexes of Shipment
type iShipment struct {
	Primary      modeled.Key[Shipment]
	ICarrier     modeled.Key[Shipment]
	IStatus      modeled.Key[Shipment]
	IShippedAt   modeled.Key[Shipment]
	IDeliveredAt modeled.Key[Shipment]
	UIOrderID    modeled.Key[Shipment]
	UITrackingNo modeled.Key[Shipment]
}

// tShipment includes modeled table, indexes and column list.
type tShipment struct {
	modeled.Table[Shipment]
	I iShipment

	ID modeled.TCol[Shipment, uint64]
	// @rel Order.OrderID
	OrderID modeled.TCol[Shipment, OrderID]
	// Carrier 物流运营商
	Carrier modeled.TCol[Shipment, string]
	// TrackingNo 物流单号
	TrackingNo modeled.TCol[Shipment, string]
	// Status 物流状态
	Status modeled.TCol[Shipment, enums.ShipmentStatus]
	// ShippedAt 开始运输时间
	ShippedAt modeled.TCol[Shipment, sqltime.Timestamp]
	// DeliveredAt 抵达时间
	DeliveredAt modeled.TCol[Shipment, sqltime.Timestamp]
	// CreatedAt 创建时间 秒时间戳
	CreatedAt modeled.TCol[Shipment, sqltime.Timestamp]
	// UpdatedAt 更新时间 秒时间戳
	UpdatedAt modeled.TCol[Shipment, sqltime.Timestamp]
}

// New creates a new Shipment
func (t *tShipment) New() builder.Model {
	return &Shipment{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tShipment) AssignmentFor(m *Shipment, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of Shipment
func (m Shipment) TableName() string {
	return "t_shipment"
}

// TableDesc returns descriptions of Shipment
func (m Shipment) TableDesc() []string {
	return []string{
		"Shipment 物流",
	}
}

// PrimaryKey returns column list of Shipment's primary key
func (m Shipment) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Shipment
func (m Shipment) Indexes() map[string][]string {
	return map[string][]string{
		"i_carrier": {
			"Carrier",
		},
		"i_status": {
			"Status",
		},
		"i_shipped_at": {
			"ShippedAt",
		},
		"i_delivered_at": {
			"DeliveredAt",
		},
	}
}

// UniqueIndexes returns unique index list of Shipment
func (m Shipment) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_order_id": {
			"OrderID",
		},
		"ui_tracking_no": {
			"TrackingNo",
		},
	}
}

// Create inserts Shipment to database
func (m *Shipment) Create(ctx context.Context) error {
	m.MarkCreatedAt()
	cols, values := helper.ColumnsAndValuesForInsertion(m)
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TShipment,
			builder.Comment("Shipment.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch Shipment datalist with condition and additions
func (m *Shipment) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]Shipment, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("Shipment.List"),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TShipment, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]Shipment)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// FetchByID fetch Shipment by Shipment.ID
func (m *Shipment) FetchByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TShipment.ID.AsCond(builder.Eq(m.ID)),
	}
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TShipment,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("Shipment.FetchByID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByOrderID fetch Shipment by Shipment.OrderID
func (m *Shipment) FetchByOrderID(ctx context.Context) error {
	conds := []frag.Fragment{
		TShipment.OrderID.AsCond(builder.Eq(m.OrderID)),
	}
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TShipment,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("Shipment.FetchByOrderID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByTrackingNo fetch Shipment by Shipment.TrackingNo
func (m *Shipment) FetchByTrackingNo(ctx context.Context) error {
	conds := []frag.Fragment{
		TShipment.TrackingNo.AsCond(builder.Eq(m.TrackingNo)),
	}
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TShipment,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("Shipment.FetchByTrackingNo"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// UpdateByID update Shipment by Shipment.ID
func (m *Shipment) UpdateByID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TShipment.ID.AsCond(builder.Eq(m.ID)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TShipment).
			Set(TShipment.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("Shipment.UpdateByID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByID update Shipment by Shipment.ID and retrieve record
func (m *Shipment) UpdateAndFetchByID(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByOrderID update Shipment by Shipment.OrderID
func (m *Shipment) UpdateByOrderID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TShipment.OrderID.AsCond(builder.Eq(m.OrderID)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TShipment).
			Set(TShipment.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("Shipment.UpdateByOrderID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByOrderID update Shipment by Shipment.OrderID and retrieve record
func (m *Shipment) UpdateAndFetchByOrderID(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByOrderID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByOrderID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByTrackingNo update Shipment by Shipment.TrackingNo
func (m *Shipment) UpdateByTrackingNo(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TShipment.TrackingNo.AsCond(builder.Eq(m.TrackingNo)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TShipment).
			Set(TShipment.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("Shipment.UpdateByTrackingNo"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByTrackingNo update Shipment by Shipment.TrackingNo and retrieve record
func (m *Shipment) UpdateAndFetchByTrackingNo(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByTrackingNo(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByTrackingNo(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// DeleteByID delete Shipment recode by Shipment.ID
func (m *Shipment) DeleteByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TShipment.ID.AsCond(builder.Eq(m.ID)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TShipment,
			builder.Where(builder.And(conds...)),
			builder.Comment("Shipment.DeleteByID"),
		),
	)
	return err
}

// DeleteByOrderID delete Shipment recode by Shipment.OrderID
func (m *Shipment) DeleteByOrderID(ctx context.Context) error {
	conds := []frag.Fragment{
		TShipment.OrderID.AsCond(builder.Eq(m.OrderID)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TShipment,
			builder.Where(builder.And(conds...)),
			builder.Comment("Shipment.DeleteByOrderID"),
		),
	)
	return err
}

// DeleteByTrackingNo delete Shipment recode by Shipment.TrackingNo
func (m *Shipment) DeleteByTrackingNo(ctx context.Context) error {
	conds := []frag.Fragment{
		TShipment.TrackingNo.AsCond(builder.Eq(m.TrackingNo)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TShipment,
			builder.Where(builder.And(conds...)),
			builder.Comment("Shipment.DeleteByTrackingNo"),
		),
	)
	return err
}
