// Code generated by genx:model DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/xoctopus/sqlx/example/enums"
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TShipment *tShipment

func init() {
	m := modeled.M[Shipment]()
	TShipment = &tShipment{
		Table: m,
		I: iShipment{
			Primary:      m.MK("primary"),
			ICarrier:     m.MK("i_carrier"),
			IStatus:      m.MK("i_status"),
			IShippedAt:   m.MK("i_shipped_at"),
			IDeliveredAt: m.MK("i_delivered_at"),
			UIOrderID:    m.MK("ui_order_id"),
			UITrackingNo: m.MK("ui_tracking_no"),
		},
		ID:          modeled.CT[Shipment, uint64](m.C("ID")),
		OrderID:     modeled.CT[Shipment, OrderID](m.C("OrderID")),
		Carrier:     modeled.CT[Shipment, string](m.C("Carrier")),
		TrackingNo:  modeled.CT[Shipment, string](m.C("TrackingNo")),
		Status:      modeled.CT[Shipment, enums.ShipmentStatus](m.C("Status")),
		ShippedAt:   modeled.CT[Shipment, sqltime.Timestamp](m.C("ShippedAt")),
		DeliveredAt: modeled.CT[Shipment, sqltime.Timestamp](m.C("DeliveredAt")),
		CreatedAt:   modeled.CT[Shipment, sqltime.Timestamp](m.C("CreatedAt")),
		UpdatedAt:   modeled.CT[Shipment, sqltime.Timestamp](m.C("UpdatedAt")),
	}
	Catalog.Add(TShipment)
}

// iShipment includes all modeled indexes of Shipment
type iShipment struct {
	Primary      modeled.Key[Shipment]
	ICarrier     modeled.Key[Shipment]
	IStatus      modeled.Key[Shipment]
	IShippedAt   modeled.Key[Shipment]
	IDeliveredAt modeled.Key[Shipment]
	UIOrderID    modeled.Key[Shipment]
	UITrackingNo modeled.Key[Shipment]
}

// tShipment includes modeled table, indexes and column list.
type tShipment struct {
	modeled.Table[Shipment]
	I       iShipment
	session string

	ID modeled.TCol[Shipment, uint64]
	// @rel Order.OrderID
	OrderID modeled.TCol[Shipment, OrderID]
	// Carrier 物流运营商
	Carrier modeled.TCol[Shipment, string]
	// TrackingNo 物流单号
	TrackingNo modeled.TCol[Shipment, string]
	// Status 物流状态
	Status modeled.TCol[Shipment, enums.ShipmentStatus]
	// ShippedAt 开始运输时间
	ShippedAt modeled.TCol[Shipment, sqltime.Timestamp]
	// DeliveredAt 抵达时间
	DeliveredAt modeled.TCol[Shipment, sqltime.Timestamp]
	// CreatedAt 创建时间 秒时间戳
	CreatedAt modeled.TCol[Shipment, sqltime.Timestamp]
	// UpdatedAt 更新时间 秒时间戳
	UpdatedAt modeled.TCol[Shipment, sqltime.Timestamp]
}

// New creates a new Shipment
func (t *tShipment) New() builder.Model {
	return &Shipment{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tShipment) AssignmentFor(m *Shipment, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// WithSession with session for tShipment
func (t *tShipment) WithSession(s string) *tShipment {
	t2 := *t
	t2.session = s
	return &t2
}

// Session returns session of tShipment
func (t tShipment) Session() string {
	return t.session
}

// TableName returns database table name of Shipment
func (m Shipment) TableName() string {
	return "t_shipment"
}

// TableDesc returns descriptions of Shipment
func (m Shipment) TableDesc() []string {
	return []string{
		"Shipment 物流",
	}
}

// PrimaryKey returns column list of Shipment's primary key
func (m Shipment) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Shipment
func (m Shipment) Indexes() map[string][]string {
	return map[string][]string{
		"i_carrier": {
			"Carrier",
		},
		"i_status": {
			"Status",
		},
		"i_shipped_at": {
			"ShippedAt",
		},
		"i_delivered_at": {
			"DeliveredAt",
		},
	}
}

// UniqueIndexes returns unique index list of Shipment
func (m Shipment) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_order_id": {
			"OrderID",
		},
		"ui_tracking_no": {
			"TrackingNo",
		},
	}
}
