// Code generated by genx:model DO NOT EDIT.
package models

import (
	"reflect"

	"github.com/xoctopus/sqlx/example/enums"
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TUser *tUser

func init() {
	m := modeled.M[User]()
	TUser = &tUser{
		Table: m,
		I: iUser{
			Primary:    m.MK("primary"),
			UIUsername: m.MK("ui_username"),
			IStatus:    m.MK("i_status"),
			ICreatedAt: m.MK("i_created_at"),
			UIUserID:   m.MK("ui_user_id"),
		},
		ID:        modeled.CT[User, uint64](m.C("ID")),
		UserID:    modeled.CT[User, UserID](m.C("UserID")),
		Username:  modeled.CT[User, string](m.C("Username")),
		Email:     modeled.CT[User, string](m.C("Email")),
		Phone:     modeled.CT[User, string](m.C("Phone")),
		Status:    modeled.CT[User, enums.UserStatus](m.C("Status")),
		CreatedAt: modeled.CT[User, sqltime.Datetime](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[User, sqltime.Datetime](m.C("UpdatedAt")),
		DeletedAt: modeled.CT[User, sqltime.Datetime](m.C("DeletedAt")),
	}
	Catalog.Add(TUser)
}

// iUser includes all modeled indexes of User
type iUser struct {
	Primary    modeled.Key[User]
	UIUsername modeled.Key[User]
	IStatus    modeled.Key[User]
	ICreatedAt modeled.Key[User]
	UIUserID   modeled.Key[User]
}

// tUser includes modeled table, indexes and column list.
type tUser struct {
	modeled.Table[User]
	I       iUser
	session string

	ID modeled.TCol[User, uint64]
	// @rel User.UserID
	UserID modeled.TCol[User, UserID]
	// Username 用户名
	Username modeled.TCol[User, string]
	// Email 邮箱
	Email modeled.TCol[User, string]
	// Phone 电话
	Phone modeled.TCol[User, string]
	// Status 用户状态
	Status modeled.TCol[User, enums.UserStatus]
	// CreatedAt 创建日期时间(秒)
	CreatedAt modeled.TCol[User, sqltime.Datetime]
	// UpdatedAt 更新日期时间(秒)
	UpdatedAt modeled.TCol[User, sqltime.Datetime]
	// DeletedAt 删除日期时间(秒)
	DeletedAt modeled.TCol[User, sqltime.Datetime]
}

// New creates a new User
func (t *tUser) New() builder.Model {
	return &User{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tUser) AssignmentFor(m *User, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// WithSession with session for tUser
func (t *tUser) WithSession(s string) *tUser {
	t2 := *t
	t2.session = s
	return &t2
}

// Session returns session of tUser
func (t tUser) Session() string {
	return t.session
}

// TableName returns database table name of User
func (m User) TableName() string {
	return "t_user"
}

// TableDesc returns descriptions of User
func (m User) TableDesc() []string {
	return []string{
		"User 用户",
	}
}

// PrimaryKey returns column list of User's primary key
func (m User) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of User
func (m User) Indexes() map[string][]string {
	return map[string][]string{
		"ui_username": {
			"Username",
		},
		"i_status": {
			"Status",
		},
		"i_created_at": {
			"CreatedAt",
		},
	}
}

// UniqueIndexes returns unique index list of User
func (m User) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_user_id": {
			"UserID",
		},
	}
}
