// Code generated by genx:doc DO NOT EDIT.
package models

import (
	"github.com/xoctopus/x/docx"
)

func (v *Order) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "CreationModificationTime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelUser, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrder, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OrderData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.CreationModificationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"订单", "@attr TableName=t_order", "@attr Register=Catalog", "@def pk ID", "@def u_idx ui_order_id  OrderID", "@def idx   i_status     Status", "@def idx   i_created_at CreatedAt", "@def idx   i_updated_at UpdatedAt"}, true
}

func (v *OrderID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *RelOrder) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrderID":
			return []string{"@rel Order.OrderID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *OrderData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrderNo":
			return []string{"订单编号"}, true
		case "Amount":
			return []string{"订单金额"}, true
		case "Currency":
			return []string{"结算币种"}, true
		case "PaidAt":
			return []string{"订单支付时间"}, true
		case "CanceledAt":
			return []string{"订单取消时间"}, true
		case "Status":
			return []string{"订单状态"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *OrderSnapshot) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "CreationTime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrder, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelProduct, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OrderSnapshotData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.CreationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"订单快照", "@attr TableName=t_order_snapshot", "@attr Register=Catalog", "@def pk ID", "@def u_idx ui_order_id    OrderID", "@def idx   i_product_name ProductName", "@def idx   i_created_at   CreatedAt"}, true
}

func (v *OrderSnapshotData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ProductSKU":
			return []string{"产品SKU"}, true
		case "ProductName":
			return []string{"产品名称 Product.Name"}, true
		case "Price":
			return []string{"产品单价 Product.Price"}, true
		case "Quantity":
			return []string{"订单产品数量"}, true
		case "Subtotal":
			return []string{"订单金额"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Product) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "CreationModificationDeletionTime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelProduct, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.ProductData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.CreationModificationDeletionTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"商品", "@attr TableName=t_product", "@attr Register=Catalog", "@def pk ID", "@def u_idx ui_product_id  ProductID,DeletedAt", "@def idx   i_product_name Name", "@def idx   i_status       Status", "@def idx   i_updated_at   UpdatedAt"}, true
}

func (v *ProductID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *RelProduct) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ProductID":
			return []string{"@rel Product.ProductID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *ProductData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "SKU":
			return []string{"库存标签"}, true
		case "Name":
			return []string{"产品名称"}, true
		case "Description":
			return []string{"产品描述"}, true
		case "Price":
			return []string{"单价"}, true
		case "Currency":
			return []string{"货币"}, true
		case "Status":
			return []string{"产品销售状态"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *Shipment) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "CreationModificationTime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrder, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.ShipmentData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.CreationModificationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"物流", "@attr TableName=t_shipment", "@attr Register=Catalog", "@def pk ID", "@def u_idx ui_order_id    OrderID", "@def u_idx ui_tracking_no TrackingNo", "@def idx   i_carrier      Carrier", "@def idx   i_status       Status", "@def idx   i_shipped_at   ShippedAt", "@def idx   i_delivered_at DeliveredAt"}, true
}

func (v *ShipmentData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Carrier":
			return []string{"物流运营商"}, true
		case "TrackingNo":
			return []string{"物流单号"}, true
		case "Status":
			return []string{"物流状态"}, true
		case "ShippedAt":
			return []string{"开始运输时间"}, true
		case "DeliveredAt":
			return []string{"抵达时间"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *User) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "OperationDatetime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelUser, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.UserData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OperationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"用户", "@attr TableName=t_user", "@attr Register=Catalog", "@def pk ID", "@def u_idx ui_user_id   UserID", "@def idx   ui_username  Username", "@def idx   i_status     Status", "@def idx   i_created_at CreatedAt"}, true
}

func (v *UserID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *RelUser) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UserID":
			return []string{"@rel User.UserID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *UserData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Username":
			return []string{"用户名"}, true
		case "Email":
			return []string{"邮箱"}, true
		case "Phone":
			return []string{"电话"}, true
		case "Status":
			return []string{"用户状态"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}
