// Code generated by genx:enum@(devel) DO NOT EDIT.
package testdata

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[Gender] = (*Gender)(nil)

// ParseGender parse Gender from key
func ParseGender(key string) (Gender, error) {
	switch key {
	case "MALE":
		return GENDER__MALE, nil
	case "FEMALE":
		return GENDER__FEMALE, nil
	default:
		var v Gender
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return GENDER_UNKNOWN, enumx.ParseErrorFor[Gender](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (Gender) EnumValues() []any {
	return []any{
		GENDER__MALE,
		GENDER__FEMALE,
	}
}

// Values returns enum value list of Gender
func (Gender) Values() []Gender {
	return []Gender{
		GENDER__MALE,
		GENDER__FEMALE,
	}
}

// String returns v's string as key
func (v Gender) String() string {
	switch v {
	case GENDER__MALE:
		return "MALE"
	case GENDER__FEMALE:
		return "FEMALE"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v Gender) Text() string {
	switch v {
	case GENDER__MALE:
		return "MALE"
	case GENDER__FEMALE:
		return "FEMALE"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v Gender) IsZero() bool {
	return v == GENDER_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v Gender) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *Gender) UnmarshalText(data []byte) error {
	vv, err := ParseGender(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Name describes Name attribute
func (v Gender) Name() string {
	switch v {
	case GENDER__MALE:
		return "男"
	case GENDER__FEMALE:
		return "女"
	default:
		return ""
	}
}

// Short describes Short attribute
func (v Gender) Short() string {
	switch v {
	case GENDER__MALE:
		return "M"
	case GENDER__FEMALE:
		return "F"
	default:
		return ""
	}
}

// Value implements driver.Valuer
func (v Gender) Value() (driver.Value, error) {
	return v.String(), nil
}

// Scan implements sql.Scanner
func (v *Gender) Scan(src any) error {
	var data []byte
	switch x := src.(type) {
	case string:
		data = []byte(x)
	case []byte:
		data = x
	default:
		return fmt.Errorf("cannot scan %T value from `%T`", v, x)
	}
	return v.UnmarshalText(data)
}
