// Code generated by model DO NOT EDIT.
package testdata

import (
	"context"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
)

// TableName returns database table name of NoIndexDef
func (m NoIndexDef) TableName() string {
	return "t_no_index_def"
}

// TableDesc returns descriptions of NoIndexDef
func (m NoIndexDef) TableDesc() []string {
	return []string{
		"NoIndexDef",
	}
}

// PrimaryKey returns column list of NoIndexDef's primary key
func (m NoIndexDef) PrimaryKey() []string {
	return []string{}
}

// Indexes returns index list of NoIndexDef
func (m NoIndexDef) Indexes() map[string][]string {
	return map[string][]string{}
}

// UniqueIndexes returns unique index list of NoIndexDef
func (m NoIndexDef) UniqueIndexes() map[string][]string {
	return map[string][]string{}
}

// iNoIndexDef includes all modeled indexes of NoIndexDef
type iNoIndexDef struct {
}

// tNoIndexDef includes modeled table, indexes and column list.
type tNoIndexDef struct {
	modeled.Table[NoIndexDef]
	I iNoIndexDef
}

// New creates a new NoIndexDef
func (tNoIndexDef) New() builder.Model {
	return &NoIndexDef{}
}

var TNoIndexDef *tNoIndexDef

func init() {
	m := modeled.M[NoIndexDef](context.Background())
	TNoIndexDef = &tNoIndexDef{
		Table: m,
		I:     iNoIndexDef{},
	}
}
