// Code generated by genx:model DO NOT EDIT.
package testdata

import (
	"context"
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
)

var TNoIndexDef *tNoIndexDef

func init() {
	m := modeled.M[NoIndexDef]()
	TNoIndexDef = &tNoIndexDef{
		Table: m,
		I:     iNoIndexDef{},
	}
}

// iNoIndexDef includes all modeled indexes of NoIndexDef
type iNoIndexDef struct {
}

// tNoIndexDef includes modeled table, indexes and column list.
type tNoIndexDef struct {
	modeled.Table[NoIndexDef]
	I iNoIndexDef
}

// New creates a new NoIndexDef
func (t *tNoIndexDef) New() builder.Model {
	return &NoIndexDef{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tNoIndexDef) AssignmentFor(m *NoIndexDef, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of NoIndexDef
func (m NoIndexDef) TableName() string {
	return "t_no_index_def"
}

// TableDesc returns descriptions of NoIndexDef
func (m NoIndexDef) TableDesc() []string {
	return []string{
		"NoIndexDef",
	}
}

// PrimaryKey returns column list of NoIndexDef's primary key
func (m NoIndexDef) PrimaryKey() []string {
	return []string{}
}

// Indexes returns index list of NoIndexDef
func (m NoIndexDef) Indexes() map[string][]string {
	return map[string][]string{}
}

// UniqueIndexes returns unique index list of NoIndexDef
func (m NoIndexDef) UniqueIndexes() map[string][]string {
	return map[string][]string{}
}

// Create inserts NoIndexDef to database
func (m *NoIndexDef) Create(ctx context.Context) error {
	cols, values := helper.ColumnsAndValuesForInsertion(m)
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TNoIndexDef,
			builder.Comment("NoIndexDef.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch NoIndexDef datalist with condition and additions
func (m *NoIndexDef) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]NoIndexDef, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("NoIndexDef.List"),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TNoIndexDef, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]NoIndexDef)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}
