// Code generated by genx:model DO NOT EDIT.
package testdata

import (
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TOrg *tOrg

func init() {
	m := modeled.M[Org]()
	TOrg = &tOrg{
		Table: m,
		I: iOrg{
			Primary:      m.MK("primary"),
			IName:        m.MK("i_name"),
			IBelonged:    m.MK("i_belonged"),
			UIOrgID:      m.MK("ui_org_id"),
			UIOrgManager: m.MK("ui_org_manager"),
		},
		ID:        modeled.CT[Org, uint64](m.C("ID")),
		OrgID:     modeled.CT[Org, OrgID](m.C("OrgID")),
		Name:      modeled.CT[Org, string](m.C("Name")),
		Belonged:  modeled.CT[Org, UserID](m.C("Belonged")),
		Manager:   modeled.CT[Org, UserID](m.C("Manager")),
		CreatedAt: modeled.CT[Org, sqltime.Timestamp](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[Org, sqltime.Timestamp](m.C("UpdatedAt")),
		DeletedAt: modeled.CT[Org, sqltime.Timestamp](m.C("DeletedAt")),
	}
}

// iOrg includes all modeled indexes of Org
type iOrg struct {
	Primary      modeled.Key[Org]
	IName        modeled.Key[Org]
	IBelonged    modeled.Key[Org]
	UIOrgID      modeled.Key[Org]
	UIOrgManager modeled.Key[Org]
}

// tOrg includes modeled table, indexes and column list.
type tOrg struct {
	modeled.Table[Org]
	I iOrg

	ID modeled.TCol[Org, uint64]
	// OrgID 组织ID
	OrgID modeled.TCol[Org, OrgID]
	// Name 组织名称
	Name modeled.TCol[Org, string]
	// Belonged 组织归属组织ID
	Belonged modeled.TCol[Org, UserID]
	// Manager 组织管理者ID
	Manager modeled.TCol[Org, UserID]
	// CreatedAt 创建时间 秒时间戳
	CreatedAt modeled.TCol[Org, sqltime.Timestamp]
	// UpdatedAt 更新时间 秒时间戳
	UpdatedAt modeled.TCol[Org, sqltime.Timestamp]
	// DeletedAt 删除时间 秒时间戳
	DeletedAt modeled.TCol[Org, sqltime.Timestamp]
}

// New creates a new Org
func (t *tOrg) New() builder.Model {
	return &Org{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tOrg) AssignmentFor(m *Org, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of Org
func (m Org) TableName() string {
	return "t_org"
}

// TableDesc returns descriptions of Org
func (m Org) TableDesc() []string {
	return []string{
		"Org 组织",
	}
}

// PrimaryKey returns column list of Org's primary key
func (m Org) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Org
func (m Org) Indexes() map[string][]string {
	return map[string][]string{
		"i_name": {
			"Name",
			"DeletedAt",
		},
		"i_belonged": {
			"Belonged",
		},
	}
}

// UniqueIndexes returns unique index list of Org
func (m Org) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_org_id": {
			"OrgID",
			"DeletedAt",
		},
		"ui_org_manager": {
			"OrgID",
			"Manager",
			"DeletedAt",
		},
	}
}
