// Code generated by model DO NOT EDIT.
package testdata

import (
	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types"
)

// TableName returns database table name of Org
func (m Org) TableName() string {
	return "t_org"
}

// TableDesc returns descriptions of Org
func (m Org) TableDesc() []string {
	return []string{
		"Org 组织",
	}
}

// PrimaryKey returns column list of Org's primary key
func (m Org) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of Org
func (m Org) Indexes() map[string][]string {
	return map[string][]string{
		"i_name": {
			"Name",
			"DeletedAt",
		},
		"i_belonged": {
			"Belonged",
		},
	}
}

// UniqueIndexes returns unique index list of Org
func (m Org) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_org_id": {
			"OrgID",
			"DeletedAt",
		},
		"ui_org_manager": {
			"OrgID",
			"Manager",
			"DeletedAt",
		},
	}
}

// iOrg includes all modeled indexes of Org
type iOrg struct {
	Primary      modeled.Key[Org]
	IName        modeled.Key[Org]
	IBelonged    modeled.Key[Org]
	UIOrgID      modeled.Key[Org]
	UIOrgManager modeled.Key[Org]
}

// tOrg includes modeled table, indexes and column list.
type tOrg struct {
	modeled.Table[Org]
	I iOrg

	ID modeled.TCol[Org, uint64]
	// OrgID 组织ID
	OrgID modeled.TCol[Org, OrgID]
	// Name 组织名称
	Name modeled.TCol[Org, string]
	// Belonged 组织归属组织ID
	Belonged modeled.TCol[Org, UserID]
	// Manager 组织管理者ID
	Manager   modeled.TCol[Org, UserID]
	CreatedAt modeled.TCol[Org, types.Timestamp]
	UpdatedAt modeled.TCol[Org, types.Timestamp]
	DeletedAt modeled.TCol[Org, types.Timestamp]
}

// New creates a new Org
func (tOrg) New() builder.Model {
	return &Org{}
}

var TOrg *tOrg

func init() {
	m := modeled.M[Org]()
	TOrg = &tOrg{
		Table: m,
		I: iOrg{
			Primary:      m.MK("primary"),
			IName:        m.MK("i_name"),
			IBelonged:    m.MK("i_belonged"),
			UIOrgID:      m.MK("ui_org_id"),
			UIOrgManager: m.MK("ui_org_manager"),
		},
		ID:        modeled.CT[Org, uint64](m.C("ID")),
		OrgID:     modeled.CT[Org, OrgID](m.C("OrgID")),
		Name:      modeled.CT[Org, string](m.C("Name")),
		Belonged:  modeled.CT[Org, UserID](m.C("Belonged")),
		Manager:   modeled.CT[Org, UserID](m.C("Manager")),
		CreatedAt: modeled.CT[Org, types.Timestamp](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[Org, types.Timestamp](m.C("UpdatedAt")),
		DeletedAt: modeled.CT[Org, types.Timestamp](m.C("DeletedAt")),
	}
}
