// Code generated by genx:model@(devel) DO NOT EDIT.
package testdata

import (
	"context"
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
	"github.com/xoctopus/sqlx/pkg/types"
)

var TTestTable *tTestTable
var TagsTestTable = map[string]string{
	"f_int8":            "f_int8",
	"f_int16":           "f_int16",
	"f_int32":           "f_int32",
	"f_int64":           "f_int64",
	"f_uint8":           "f_uint8",
	"f_uint16":          "f_uint16",
	"f_uint32":          "f_uint32",
	"f_uint64":          "f_uint64",
	"f_int8_default":    "f_int8_default",
	"f_string":          "f_string",
	"f_string_w":        "f_string_w",
	"f_float32":         "f_float32",
	"f_float32_default": "f_float32_default",
	"f_decimal":         "f_decimal",
	"f_decimal_default": "f_decimal_default",
}

func init() {
	m := modeled.M[TestTable]()
	TTestTable = &tTestTable{
		Table:            m,
		I:                iTestTable{},
		Int8:             modeled.CT[TestTable, int8](m.C("Int8")),
		Int16:            modeled.CT[TestTable, int16](m.C("Int16")),
		Int32:            modeled.CT[TestTable, int32](m.C("Int32")),
		Int64:            modeled.CT[TestTable, int64](m.C("Int64")),
		Uint8:            modeled.CT[TestTable, uint8](m.C("Uint8")),
		Uint16:           modeled.CT[TestTable, uint16](m.C("Uint16")),
		Uint32:           modeled.CT[TestTable, uint32](m.C("Uint32")),
		Uint64:           modeled.CT[TestTable, uint64](m.C("Uint64")),
		Int8Default:      modeled.CT[TestTable, int8](m.C("Int8Default")),
		String_:          modeled.CT[TestTable, string](m.C("String_")),
		StringWidthFixed: modeled.CT[TestTable, string](m.C("StringWidthFixed")),
		Float32:          modeled.CT[TestTable, float32](m.C("Float32")),
		Float32Default:   modeled.CT[TestTable, float32](m.C("Float32Default")),
		Decimal:          modeled.CT[TestTable, types.Decimal](m.C("Decimal")),
		DecimalDefault:   modeled.CT[TestTable, types.Decimal](m.C("DecimalDefault")),
	}
}

// iTestTable includes all modeled indexes of TestTable
type iTestTable struct {
}

// tTestTable includes modeled table, indexes and column list.
type tTestTable struct {
	modeled.Table[TestTable]
	I      iTestTable
	schema string

	Int8             modeled.TCol[TestTable, int8]
	Int16            modeled.TCol[TestTable, int16]
	Int32            modeled.TCol[TestTable, int32]
	Int64            modeled.TCol[TestTable, int64]
	Uint8            modeled.TCol[TestTable, uint8]
	Uint16           modeled.TCol[TestTable, uint16]
	Uint32           modeled.TCol[TestTable, uint32]
	Uint64           modeled.TCol[TestTable, uint64]
	Int8Default      modeled.TCol[TestTable, int8]
	String_          modeled.TCol[TestTable, string]
	StringWidthFixed modeled.TCol[TestTable, string]
	Float32          modeled.TCol[TestTable, float32]
	Float32Default   modeled.TCol[TestTable, float32]
	Decimal          modeled.TCol[TestTable, types.Decimal]
	DecimalDefault   modeled.TCol[TestTable, types.Decimal]
}

// New creates a new TestTable
func (t *tTestTable) New() builder.Model {
	return &TestTable{}
}

// TagFor returns column tag mapping by name
func (t *tTestTable) TagFor(name string) (string, bool) {
	v, ok := TagsTestTable[name]
	return v, ok
}

// AssignmentFor returns assignment by m with expects columns
func (t *tTestTable) AssignmentFor(m *TestTable, expects ...builder.Col) builder.Assignment {
	cs := t.Pick()
	if len(expects) > 0 {
		cs = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cs.Len())
	cols := make([]builder.Col, 0, cs.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cs.Cols() {
		if !builder.GetColDef(c).AutoInc {
			cols = append(cols, c)
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(builder.ColsOf(cols...), vals...)
}

// WithSchema with schema for tTestTable
func (t *tTestTable) WithSchema(s string) builder.Table {
	t.schema = s
	return t
}

// Schema returns schema of tTestTable
func (t tTestTable) Schema() string {
	return t.schema
}

// TableName returns database table name of TestTable
func (m TestTable) TableName() string {
	return "t_test_table"
}

// TableDesc returns descriptions of TestTable
func (m TestTable) TableDesc() []string {
	return []string{
		"测试用",
	}
}

// PrimaryKey returns column list of TestTable's primary key
func (m TestTable) PrimaryKey() []string {
	return []string{}
}

// Indexes returns index list of TestTable
func (m TestTable) Indexes() map[string][]string {
	return map[string][]string{}
}

// UniqueIndexes returns unique index list of TestTable
func (m TestTable) UniqueIndexes() map[string][]string {
	return map[string][]string{}
}

// ColumnRel presents soft foreign key of columns
func (m TestTable) ColumnRel() map[string][]string {
	return map[string][]string{}
}

// Create inserts TestTable to database
func (m *TestTable) Create(ctx context.Context) error {
	cols, values := helper.CVsForInsertion(m)
	_, err := session.MustFor(ctx, TTestTable).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TTestTable,
			builder.Comment("TestTable.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch TestTable datalist with condition and additions
func (m *TestTable) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]TestTable, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("TestTable.List"),
	)
	rows, err := session.MustFor(ctx, TTestTable).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TTestTable, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]TestTable)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// Count record count of TestTable match condition
func (m *TestTable) Count(ctx context.Context, cond builder.SqlCondition) (int64, error) {
	conds := []frag.Fragment{cond}
	adds := builder.Additions{
		builder.Where(builder.And(conds...)),
		builder.Comment("TestTable.Count"),
	}
	rows, err := session.MustFor(ctx, TTestTable).Adaptor().Query(
		ctx,
		builder.Select(builder.Count()).From(TTestTable, adds...),
	)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	count := int64(0)
	if err = helper.Scan(ctx, rows, &count); err != nil {
		return 0, err
	}
	return count, nil
}
