// Code generated by genx:model DO NOT EDIT.
package testdata

import (
	"reflect"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TUser *tUser

func init() {
	m := modeled.M[User]()
	TUser = &tUser{
		Table: m,
		I: iUser{
			Primary:   m.MK("primary"),
			INickname: m.MK("i_nickname"),
			IAge:      m.MK("i_age"),
			UIUserID:  m.MK("ui_user_id"),
			UIName:    m.MK("ui_name"),
		},
		ID:        modeled.CT[User, uint64](m.C("ID")),
		UserID:    modeled.CT[User, UserID](m.C("UserID")),
		OrgID:     modeled.CT[User, OrgID](m.C("OrgID")),
		Name:      modeled.CT[User, string](m.C("Name")),
		IsMember:  modeled.CT[User, bool](m.C("IsMember")),
		RealName:  modeled.CT[User, string](m.C("RealName")),
		Username:  modeled.CT[User, string](m.C("Username")),
		Nickname:  modeled.CT[User, string](m.C("Nickname")),
		Age:       modeled.CT[User, int](m.C("Age")),
		Gender:    modeled.CT[User, Gender](m.C("Gender")),
		Asset:     modeled.CT[User, types.Decimal](m.C("Asset")),
		CreatedAt: modeled.CT[User, sqltime.Datetime](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[User, sqltime.Datetime](m.C("UpdatedAt")),
		DeletedAt: modeled.CT[User, sqltime.Datetime](m.C("DeletedAt")),
	}
}

// iUser includes all modeled indexes of User
type iUser struct {
	Primary   modeled.Key[User]
	INickname modeled.Key[User]
	IAge      modeled.Key[User]
	UIUserID  modeled.Key[User]
	UIName    modeled.Key[User]
}

// tUser includes modeled table, indexes and column list.
type tUser struct {
	modeled.Table[User]
	I iUser

	ID modeled.TCol[User, uint64]
	// UserID 用户ID
	UserID modeled.TCol[User, UserID]
	// OrgID 组织ID
	OrgID modeled.TCol[User, OrgID]
	// Name 用户姓名
	Name modeled.TCol[User, string]
	// IsMember 是否为会员
	IsMember modeled.TCol[User, bool]
	// RealName 真实姓名
	RealName modeled.TCol[User, string]
	// Username 用户姓名
	Username modeled.TCol[User, string]
	// Nickname 用户昵称
	Nickname modeled.TCol[User, string]
	// Age 年龄
	Age modeled.TCol[User, int]
	// Gender 性别
	Gender modeled.TCol[User, Gender]
	// Asset 资产 decimal(32,4)
	Asset modeled.TCol[User, types.Decimal]
	// CreatedAt 创建日期时间(秒)
	CreatedAt modeled.TCol[User, sqltime.Datetime]
	// UpdatedAt 更新日期时间(秒)
	UpdatedAt modeled.TCol[User, sqltime.Datetime]
	// DeletedAt 删除日期时间(秒)
	DeletedAt modeled.TCol[User, sqltime.Datetime]
}

// New creates a new User
func (t *tUser) New() builder.Model {
	return &User{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tUser) AssignmentFor(m *User, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of User
func (m User) TableName() string {
	return "t_user"
}

// TableDesc returns descriptions of User
func (m User) TableDesc() []string {
	return []string{
		"User 用户",
	}
}

// PrimaryKey returns column list of User's primary key
func (m User) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of User
func (m User) Indexes() map[string][]string {
	return map[string][]string{
		"i_nickname": {
			"Nickname",
			"DeletedAt",
		},
		"i_age": {
			"Age",
		},
	}
}

// UniqueIndexes returns unique index list of User
func (m User) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_user_id": {
			"UserID",
			"DeletedAt",
		},
		"ui_name": {
			"Name",
			"DeletedAt",
		},
	}
}
