// Code generated by genx:model DO NOT EDIT.
package testdata

import (
	"context"
	"database/sql/driver"
	"reflect"

	"github.com/xoctopus/x/codex"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/errors"
	"github.com/xoctopus/sqlx/pkg/frag"
	"github.com/xoctopus/sqlx/pkg/helper"
	"github.com/xoctopus/sqlx/pkg/session"
	"github.com/xoctopus/sqlx/pkg/types"
	"github.com/xoctopus/sqlx/pkg/types/sqltime"
)

var TUser *tUser

func init() {
	m := modeled.M[User]()
	TUser = &tUser{
		Table: m,
		I: iUser{
			Primary:   m.MK("primary"),
			INickname: m.MK("i_nickname"),
			IAge:      m.MK("i_age"),
			UIUserID:  m.MK("ui_user_id"),
			UIName:    m.MK("ui_name"),
		},
		ID:        modeled.CT[User, uint64](m.C("ID")),
		UserID:    modeled.CT[User, UserID](m.C("UserID")),
		OrgID:     modeled.CT[User, OrgID](m.C("OrgID")),
		Name:      modeled.CT[User, string](m.C("Name")),
		RealName:  modeled.CT[User, string](m.C("RealName")),
		Username:  modeled.CT[User, string](m.C("Username")),
		Nickname:  modeled.CT[User, string](m.C("Nickname")),
		Age:       modeled.CT[User, int](m.C("Age")),
		Gender:    modeled.CT[User, Gender](m.C("Gender")),
		Asset:     modeled.CT[User, types.Decimal](m.C("Asset")),
		CreatedAt: modeled.CT[User, sqltime.Datetime](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[User, sqltime.Datetime](m.C("UpdatedAt")),
		DeletedAt: modeled.CT[User, sqltime.Datetime](m.C("DeletedAt")),
	}
}

// iUser includes all modeled indexes of User
type iUser struct {
	Primary   modeled.Key[User]
	INickname modeled.Key[User]
	IAge      modeled.Key[User]
	UIUserID  modeled.Key[User]
	UIName    modeled.Key[User]
}

// tUser includes modeled table, indexes and column list.
type tUser struct {
	modeled.Table[User]
	I iUser

	ID modeled.TCol[User, uint64]
	// UserID 用户ID
	UserID modeled.TCol[User, UserID]
	// OrgID 组织ID
	OrgID modeled.TCol[User, OrgID]
	// Name 用户姓名
	Name modeled.TCol[User, string]
	// RealName 真实姓名
	RealName modeled.TCol[User, string]
	// Username 用户姓名
	Username modeled.TCol[User, string]
	// Nickname 用户昵称
	Nickname modeled.TCol[User, string]
	// Age 年龄
	Age modeled.TCol[User, int]
	// Gender 性别
	Gender modeled.TCol[User, Gender]
	// Asset 资产 decimal(32,4)
	Asset modeled.TCol[User, types.Decimal]
	// CreatedAt 创建日期时间(秒)
	CreatedAt modeled.TCol[User, sqltime.Datetime]
	// UpdatedAt 更新日期时间(秒)
	UpdatedAt modeled.TCol[User, sqltime.Datetime]
	// DeletedAt 删除日期时间(秒)
	DeletedAt modeled.TCol[User, sqltime.Datetime]
}

// New creates a new User
func (t *tUser) New() builder.Model {
	return &User{}
}

// AssignmentFor returns assignment by m with expects columns
func (t *tUser) AssignmentFor(m *User, expects ...builder.Col) builder.Assignment {
	cols := t.Pick()
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	vals := make([]any, 0, cols.Len())
	rv := reflect.ValueOf(m).Elem()
	for c := range cols.Cols() {
		if !builder.GetColDef(c).AutoInc {
			vals = append(vals, rv.FieldByName(c.FieldName()).Interface())
		}
	}
	return builder.ColumnsAndValues(cols, vals...)
}

// TableName returns database table name of User
func (m User) TableName() string {
	return "t_user"
}

// TableDesc returns descriptions of User
func (m User) TableDesc() []string {
	return []string{
		"User 用户",
	}
}

// PrimaryKey returns column list of User's primary key
func (m User) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of User
func (m User) Indexes() map[string][]string {
	return map[string][]string{
		"i_nickname": {
			"Nickname",
			"DeletedAt",
		},
		"i_age": {
			"Age",
		},
	}
}

// UniqueIndexes returns unique index list of User
func (m User) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_user_id": {
			"UserID",
			"DeletedAt",
		},
		"ui_name": {
			"Name",
			"DeletedAt",
		},
	}
}

// Create inserts User to database
func (m *User) Create(ctx context.Context) error {
	m.MarkCreatedAt()
	cols, values := helper.ColumnsAndValuesForInsertion(m)
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Insert().Into(
			TUser,
			builder.Comment("User.Create"),
		).Values(cols, values...),
	)
	return err
}

// List fetch User datalist with condition and additions
func (m *User) List(ctx context.Context, cond builder.SqlCondition, adds builder.Additions, expects ...builder.Col) ([]User, error) {
	cols := frag.Fragment(nil)
	if len(expects) > 0 {
		cols = builder.ColsOf(expects...)
	}
	conds := []frag.Fragment{cond}
	deletion, _, v := m.SoftDeletion()
	conds = append(
		conds,
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Eq(v)),
	)
	adds = append(
		adds,
		builder.Where(builder.And(conds...)),
		builder.Comment("User.List"),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(cols).From(TUser, adds...),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	res := new([]User)
	if err = helper.Scan(ctx, rows, res); err != nil {
		return nil, err
	}
	return *res, nil
}

// FetchByID fetch User by User.ID
func (m *User) FetchByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
	}
	deletion, _, v := m.SoftDeletion()
	conds = append(
		conds,
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Eq(v)),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("User.FetchByID"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByUserIDAndDeletedAt fetch User by User.UserID and User.DeletedAt
func (m *User) FetchByUserIDAndDeletedAt(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
	}
	deletion, _, v := m.SoftDeletion()
	conds = append(
		conds,
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Eq(v)),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("User.FetchByUserIDAndDeletedAt"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// FetchByNameAndDeletedAt fetch User by User.Name and User.DeletedAt
func (m *User) FetchByNameAndDeletedAt(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.Name.AsCond(builder.Eq(m.Name)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
	}
	deletion, _, v := m.SoftDeletion()
	conds = append(
		conds,
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Eq(v)),
	)
	rows, err := session.For(ctx, m).Adaptor().Query(
		ctx,
		builder.Select(nil).From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Limit(1),
			builder.Comment("User.FetchByNameAndDeletedAt"),
		),
	)
	if err != nil {
		return err
	}
	defer rows.Close()
	return helper.Scan(ctx, rows, m)
}

// UpdateByID update User by User.ID
func (m *User) UpdateByID(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.UpdateByID"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByID update User by User.ID and retrieve record
func (m *User) UpdateAndFetchByID(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByID(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByID(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByUserIDAndDeletedAt update User by User.UserID and User.DeletedAt
func (m *User) UpdateByUserIDAndDeletedAt(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.UpdateByUserIDAndDeletedAt"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByUserIDAndDeletedAt update User by User.UserID and User.DeletedAt and retrieve record
func (m *User) UpdateAndFetchByUserIDAndDeletedAt(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByUserIDAndDeletedAt(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByUserIDAndDeletedAt(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// UpdateByNameAndDeletedAt update User by User.Name and User.DeletedAt
func (m *User) UpdateByNameAndDeletedAt(ctx context.Context, expects ...builder.Col) error {
	m.MarkModifiedAt()
	conds := []frag.Fragment{
		TUser.Name.AsCond(builder.Eq(m.Name)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
	}
	res, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, expects...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.UpdateByNameAndDeletedAt"),
			),
	)
	if err != nil {
		return err
	}
	effected, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if effected == 0 {
		return codex.New(errors.NOTFOUND)
	}
	return nil
}

// UpdateAndFetchByNameAndDeletedAt update User by User.Name and User.DeletedAt and retrieve record
func (m *User) UpdateAndFetchByNameAndDeletedAt(ctx context.Context, targets ...builder.Col) error {
	return session.For(ctx, m).Adaptor().Tx(
		ctx,
		func(ctx context.Context) error {
			if err := m.UpdateByNameAndDeletedAt(ctx, targets...); err != nil {
				return err
			}
			if err := m.FetchByNameAndDeletedAt(ctx); err != nil {
				return err
			}
			return nil
		},
	)
}

// DeleteByID delete User recode by User.ID
func (m *User) DeleteByID(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Comment("User.DeleteByID"),
		),
	)
	return err
}

// DeleteByUserIDAndDeletedAt delete User recode by User.UserID and User.DeletedAt
func (m *User) DeleteByUserIDAndDeletedAt(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Comment("User.DeleteByUserIDAndDeletedAt"),
		),
	)
	return err
}

// DeleteByNameAndDeletedAt delete User recode by User.Name and User.DeletedAt
func (m *User) DeleteByNameAndDeletedAt(ctx context.Context) error {
	conds := []frag.Fragment{
		TUser.Name.AsCond(builder.Eq(m.Name)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Delete().From(
			TUser,
			builder.Where(builder.And(conds...)),
			builder.Comment("User.DeleteByNameAndDeletedAt"),
		),
	)
	return err
}

// MarkDeletionByID marks User as deleted
func (m *User) MarkDeletionByID(ctx context.Context) error {
	m.MarkDeletedAt()
	deletion, modifications, v := m.SoftDeletion()
	cols := []builder.Col{TUser.C(deletion)}
	for _, f := range modifications {
		cols = append(cols, TUser.C(f))
	}
	conds := []frag.Fragment{
		TUser.ID.AsCond(builder.Eq(m.ID)),
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Neq(v)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, cols...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.MarkDeletionByID"),
			),
	)
	return err
}

// MarkDeletionByUserIDAndDeletedAt marks User as deleted
func (m *User) MarkDeletionByUserIDAndDeletedAt(ctx context.Context) error {
	m.MarkDeletedAt()
	deletion, modifications, v := m.SoftDeletion()
	cols := []builder.Col{TUser.C(deletion)}
	for _, f := range modifications {
		cols = append(cols, TUser.C(f))
	}
	conds := []frag.Fragment{
		TUser.UserID.AsCond(builder.Eq(m.UserID)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Neq(v)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, cols...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.MarkDeletionByUserIDAndDeletedAt"),
			),
	)
	return err
}

// MarkDeletionByNameAndDeletedAt marks User as deleted
func (m *User) MarkDeletionByNameAndDeletedAt(ctx context.Context) error {
	m.MarkDeletedAt()
	deletion, modifications, v := m.SoftDeletion()
	cols := []builder.Col{TUser.C(deletion)}
	for _, f := range modifications {
		cols = append(cols, TUser.C(f))
	}
	conds := []frag.Fragment{
		TUser.Name.AsCond(builder.Eq(m.Name)),
		TUser.DeletedAt.AsCond(builder.Eq(m.DeletedAt)),
		builder.CC[driver.Value](TUser.C(deletion)).AsCond(builder.Neq(v)),
	}
	_, err := session.For(ctx, m).Adaptor().Exec(
		ctx,
		builder.Update(TUser).
			Set(TUser.AssignmentFor(m, cols...)).
			Where(
				builder.And(conds...),
				builder.Comment("User.MarkDeletionByNameAndDeletedAt"),
			),
	)
	return err
}
