// Package testdata GENERATED BY model DO NOT EDIT
package testdata

import (
	"context"

	"github.com/xoctopus/sqlx/pkg/builder"
	"github.com/xoctopus/sqlx/pkg/builder/modeled"
	"github.com/xoctopus/sqlx/pkg/types"
)

// TableName returns database table name of User
func (m User) TableName() string {
	return "users"
}

// TableDesc returns descriptions of User
func (m User) TableDesc() []string {
	return []string{
		"User 用户",
	}
}

// PrimaryKey returns column list of User's primary key
func (m User) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

// Indexes returns index list of User
func (m User) Indexes() map[string][]string {
	return map[string][]string{
		"i_nickname": {
			"Nickname",
			"DeletedAt",
		},
	}
}

// UniqueIndexes returns unique index list of User
func (m User) UniqueIndexes() map[string][]string {
	return map[string][]string{
		"ui_user_id": {
			"UserID",
			"DeletedAt",
		},
		"ui_name": {
			"Name",
			"DeletedAt",
		},
	}
}

// iUser includes all modeled indexes of User
type iUser struct {
	Primary   modeled.Key[User]
	INickname modeled.Key[User]
	UIUserID  modeled.Key[User]
	UIName    modeled.Key[User]
}

// tUser includes modeled table, indexes and column list.
type tUser struct {
	modeled.Table[User]
	I iUser

	ID modeled.TCol[User, uint64]
	// UserID 用户ID
	UserID modeled.TCol[User, UserID]
	// OrgID 组织ID
	OrgID modeled.TCol[User, OrgID]
	// Name 用户姓名
	Name modeled.TCol[User, string]
	// Nickname 用户昵称
	Nickname modeled.TCol[User, string]
	// Age 年龄
	Age modeled.TCol[User, int]
	// Gender 性别
	Gender modeled.TCol[User, Gender]
	// Asset 资产 decimal(32,4)
	Asset     modeled.TCol[User, types.Decimal]
	CreatedAt modeled.TCol[User, types.Timestamp]
	UpdatedAt modeled.TCol[User, types.Timestamp]
	DeletedAt modeled.TCol[User, types.Timestamp]
}

// New creates a new User
func (tUser) New() builder.Model {
	return &User{}
}

var TUser *tUser

func init() {
	m := modeled.M[User](context.Background())
	TUser = &tUser{
		Table: m,
		I: iUser{
			Primary:   m.MK("primary"),
			INickname: m.MK("i_nickname"),
			UIUserID:  m.MK("ui_user_id"),
			UIName:    m.MK("ui_name"),
		},
		ID:        modeled.CT[User, uint64](m.C("ID")),
		UserID:    modeled.CT[User, UserID](m.C("UserID")),
		OrgID:     modeled.CT[User, OrgID](m.C("OrgID")),
		Name:      modeled.CT[User, string](m.C("Name")),
		Nickname:  modeled.CT[User, string](m.C("Nickname")),
		Age:       modeled.CT[User, int](m.C("Age")),
		Gender:    modeled.CT[User, Gender](m.C("Gender")),
		Asset:     modeled.CT[User, types.Decimal](m.C("Asset")),
		CreatedAt: modeled.CT[User, types.Timestamp](m.C("CreatedAt")),
		UpdatedAt: modeled.CT[User, types.Timestamp](m.C("UpdatedAt")),
		DeletedAt: modeled.CT[User, types.Timestamp](m.C("DeletedAt")),
	}
}
