// Code generated by genx:doc DO NOT EDIT.
package testdata

import (
	"github.com/xoctopus/x/docx"
)

func (v *NotStruct) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{""}, true
}

func (v *Gender) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"", "@def storage=text"}, true
}

func (v *NoIndexDef) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{""}, true
}

func (v *Org) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "OperationTime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrg, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OrgData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OperationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"组织", "@def pk ID", "@def uidx ui_org_id      OrgID;DeletedAt", "@def uidx ui_org_manager OrgID;Manager;DeletedAt", "@def idx  i_name         Name;DeletedAt", "@def idx  i_belonged     Belonged"}, true
}

func (v *RelOrg) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{"组织ID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *OrgData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"组织名称"}, true
		case "Belonged":
			return []string{"组织归属组织ID"}, true
		case "Manager":
			return []string{"组织管理者ID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *OrgID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *User) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AutoIncID":
			return []string{}, true
		case "OperationDatetime":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelUser, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrg, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.UserData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OperationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"用户", "@attr TableName=t_user", "@def pk ID", "@def u_idx ui_user_id       UserID;DeletedAt", "@def u_idx ui_name          Name;DeletedAt", "@def idx   i_nickname,BTREE Nickname;DeletedAt", "@def idx   i_age            Age"}, true
}

func (v *RelUser) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UserID":
			return []string{"用户ID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *UserData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"用户姓名"}, true
		case "IsMember":
			return []string{"是否为会员"}, true
		case "RealName":
			return []string{"真实姓名"}, true
		case "Username":
			return []string{"用户姓名"}, true
		case "Nickname":
			return []string{"用户昵称"}, true
		case "Age":
			return []string{"年龄"}, true
		case "Gender":
			return []string{"性别"}, true
		case "Asset":
			return []string{"资产 decimal(32,4)"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *UserID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
