// Code generated by genx:doc@(devel) DO NOT EDIT.
package testdata

import (
	"github.com/xoctopus/x/docx"
)

func (v *NotStruct) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *Gender) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *NoIndexDef) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *Org) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrg, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OrgData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OperationTime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"组织"}, true
}

func (v *RelOrg) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{"组织ID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *OrgData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"组织名称"}, true
		case "Belonged":
			return []string{"组织归属组织ID"}, true
		case "Manager":
			return []string{"组织管理者ID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *OrgID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *TestTable) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Int8":
			return []string{}, true
		case "Int16":
			return []string{}, true
		case "Int32":
			return []string{}, true
		case "Int64":
			return []string{}, true
		case "Uint8":
			return []string{}, true
		case "Uint16":
			return []string{}, true
		case "Uint32":
			return []string{}, true
		case "Uint64":
			return []string{}, true
		case "Int8Default":
			return []string{}, true
		case "String_":
			return []string{}, true
		case "StringWidthFixed":
			return []string{}, true
		case "Float32":
			return []string{}, true
		case "Float32Default":
			return []string{}, true
		case "Decimal":
			return []string{}, true
		case "DecimalDefault":
			return []string{}, true
		}
		return []string{}, false
	}
	return []string{"测试用"}, true
}

func (v *User) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := docx.Of(&v.AutoIncID, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelUser, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.RelOrg, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.UserData, "", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.OperationDatetime, "", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"用户"}, true
}

func (v *RelUser) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UserID":
			return []string{"用户ID"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *UserData) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"用户姓名"}, true
		case "IsMember":
			return []string{"是否为会员"}, true
		case "RealName":
			return []string{"真实姓名"}, true
		case "Username":
			return []string{"用户姓名"}, true
		case "Nickname":
			return []string{"用户昵称"}, true
		case "Age":
			return []string{"年龄"}, true
		case "Gender":
			return []string{"性别"}, true
		case "Asset":
			return []string{"资产"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *UserID) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}
